linters:
  disable-all: true
  enable:
    - errorlint
    - gofmt
    - gosimple
    - govet
    - importas
    - revive
    - typecheck
    - unused
    - staticcheck

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "ST1003:"
      linters:
        - stylecheck
    # FIXME: Disabled until golangci-lint updates stylecheck with this fix:
    # https://github.com/dominikh/go-tools/issues/389
    - text: "ST1016:"
      linters:
        - stylecheck

    - text: "SA4006:"
      linters:
        - staticcheck

    - text: "SA1019:"
      linters:
        - staticcheck

    - path: "migrations"
      text: "SA1019:"
      linters:
        - staticcheck

  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  revive:
    rules:
      - name: duplicated-imports
        severity: warning
        disabled: false
      - name: range-val-address
        severity: warning
        disabled: false
  importas:
    # List of aliases
    alias:
      - pkg: github.com/joltify-finance/joltify_lending/x/third_party_dydx/subaccounts/types
        alias: satypes
      - pkg: github.com/joltify-finance/joltify_lending/testutil/dydx/testutil/constants
        alias: constants
