// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: joltify/spv/deposit.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DepositorInfo_DEPOSITTYPE int32

const (
	DepositorInfo_withdraw_proposal DepositorInfo_DEPOSITTYPE = 0
	DepositorInfo_transfer_request  DepositorInfo_DEPOSITTYPE = 1
	DepositorInfo_deposit_close     DepositorInfo_DEPOSITTYPE = 2
	DepositorInfo_unset             DepositorInfo_DEPOSITTYPE = 3
	DepositorInfo_processed         DepositorInfo_DEPOSITTYPE = 4
	DepositorInfo_deactive          DepositorInfo_DEPOSITTYPE = 5
)

var DepositorInfo_DEPOSITTYPE_name = map[int32]string{
	0: "withdraw_proposal",
	1: "transfer_request",
	2: "deposit_close",
	3: "unset",
	4: "processed",
	5: "deactive",
}

var DepositorInfo_DEPOSITTYPE_value = map[string]int32{
	"withdraw_proposal": 0,
	"transfer_request":  1,
	"deposit_close":     2,
	"unset":             3,
	"processed":         4,
	"deactive":          5,
}

func (x DepositorInfo_DEPOSITTYPE) String() string {
	return proto.EnumName(DepositorInfo_DEPOSITTYPE_name, int32(x))
}

func (DepositorInfo_DEPOSITTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5bb054114dab9679, []int{0, 0}
}

type DepositorInfo struct {
	InvestorId                 string                                        `protobuf:"bytes,1,opt,name=investor_id,json=investorId,proto3" json:"investor_id,omitempty"`
	DepositorAddress           github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,2,opt,name=depositor_address,json=depositorAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"depositor_address,omitempty"`
	PoolIndex                  string                                        `protobuf:"bytes,3,opt,name=pool_index,json=poolIndex,proto3" json:"pool_index,omitempty"`
	LockedAmount               types.Coin                                    `protobuf:"bytes,4,opt,name=locked_amount,json=lockedAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"locked_amount"`
	WithdrawalAmount           types.Coin                                    `protobuf:"bytes,5,opt,name=withdrawal_amount,json=withdrawalAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"withdrawal_amount"`
	IncentiveAmount            types.Coin                                    `protobuf:"bytes,6,opt,name=incentive_amount,json=incentiveAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"incentive_amount"`
	LinkedNFT                  []string                                      `protobuf:"bytes,7,rep,name=linkedNFT,proto3" json:"linkedNFT,omitempty"`
	DepositType                DepositorInfo_DEPOSITTYPE                     `protobuf:"varint,8,opt,name=deposit_type,json=depositType,proto3,enum=joltify.spv.DepositorInfo_DEPOSITTYPE" json:"deposit_type,omitempty"`
	PendingInterest            types.Coin                                    `protobuf:"bytes,9,opt,name=pending_interest,json=pendingInterest,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"pending_interest"`
	TotalPaidLiquidationAmount github_com_cosmos_cosmos_sdk_types.Int        `protobuf:"bytes,10,opt,name=total_paid_liquidation_amount,json=totalPaidLiquidationAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"total_paid_liquidation_amount"`
}

func (m *DepositorInfo) Reset()         { *m = DepositorInfo{} }
func (m *DepositorInfo) String() string { return proto.CompactTextString(m) }
func (*DepositorInfo) ProtoMessage()    {}
func (*DepositorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bb054114dab9679, []int{0}
}
func (m *DepositorInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DepositorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DepositorInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DepositorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositorInfo.Merge(m, src)
}
func (m *DepositorInfo) XXX_Size() int {
	return m.Size()
}
func (m *DepositorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DepositorInfo proto.InternalMessageInfo

func (m *DepositorInfo) GetInvestorId() string {
	if m != nil {
		return m.InvestorId
	}
	return ""
}

func (m *DepositorInfo) GetDepositorAddress() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.DepositorAddress
	}
	return nil
}

func (m *DepositorInfo) GetPoolIndex() string {
	if m != nil {
		return m.PoolIndex
	}
	return ""
}

func (m *DepositorInfo) GetLockedAmount() types.Coin {
	if m != nil {
		return m.LockedAmount
	}
	return types.Coin{}
}

func (m *DepositorInfo) GetWithdrawalAmount() types.Coin {
	if m != nil {
		return m.WithdrawalAmount
	}
	return types.Coin{}
}

func (m *DepositorInfo) GetIncentiveAmount() types.Coin {
	if m != nil {
		return m.IncentiveAmount
	}
	return types.Coin{}
}

func (m *DepositorInfo) GetLinkedNFT() []string {
	if m != nil {
		return m.LinkedNFT
	}
	return nil
}

func (m *DepositorInfo) GetDepositType() DepositorInfo_DEPOSITTYPE {
	if m != nil {
		return m.DepositType
	}
	return DepositorInfo_withdraw_proposal
}

func (m *DepositorInfo) GetPendingInterest() types.Coin {
	if m != nil {
		return m.PendingInterest
	}
	return types.Coin{}
}

func init() {
	proto.RegisterEnum("joltify.spv.DepositorInfo_DEPOSITTYPE", DepositorInfo_DEPOSITTYPE_name, DepositorInfo_DEPOSITTYPE_value)
	proto.RegisterType((*DepositorInfo)(nil), "joltify.spv.DepositorInfo")
}

func init() { proto.RegisterFile("joltify/spv/deposit.proto", fileDescriptor_5bb054114dab9679) }

var fileDescriptor_5bb054114dab9679 = []byte{
	// 645 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xbf, 0x6e, 0xdb, 0x3a,
	0x14, 0xc6, 0xad, 0xfc, 0xbb, 0x31, 0x6d, 0xdf, 0xab, 0xf0, 0xa6, 0x80, 0x12, 0x34, 0xb2, 0x91,
	0x21, 0xf0, 0x62, 0xa9, 0x49, 0x81, 0x4e, 0x5d, 0xe2, 0x26, 0x45, 0x05, 0x14, 0xad, 0xe1, 0x7a,
	0x69, 0x17, 0x81, 0x16, 0x8f, 0x1d, 0x36, 0x32, 0xc9, 0x88, 0x94, 0x13, 0x4f, 0x1d, 0xfa, 0x02,
	0x7d, 0x8e, 0xce, 0x79, 0x88, 0x8c, 0x41, 0xa6, 0xa2, 0x43, 0x5a, 0x24, 0x6f, 0xd1, 0xa9, 0x90,
	0x44, 0x25, 0xe9, 0x96, 0x21, 0x9d, 0x24, 0x7e, 0xe4, 0xe1, 0xef, 0x9c, 0xef, 0x1c, 0x10, 0xad,
	0x7d, 0x14, 0xb1, 0x66, 0xa3, 0x99, 0xaf, 0xe4, 0xd4, 0xa7, 0x20, 0x85, 0x62, 0xda, 0x93, 0x89,
	0xd0, 0x02, 0xd7, 0xcc, 0x96, 0xa7, 0xe4, 0x74, 0x7d, 0x2d, 0x12, 0x6a, 0x22, 0x54, 0x98, 0x6f,
	0xf9, 0xc5, 0xa2, 0x38, 0xb7, 0xbe, 0x3a, 0x16, 0x63, 0x51, 0xe8, 0xd9, 0x9f, 0x51, 0xdd, 0xe2,
	0x8c, 0x3f, 0x24, 0x0a, 0xfc, 0xe9, 0xf6, 0x10, 0x34, 0xd9, 0xf6, 0x23, 0xc1, 0xb8, 0xd9, 0x6f,
	0x8e, 0x85, 0x18, 0xc7, 0xe0, 0xe7, 0xab, 0x61, 0x3a, 0xf2, 0x35, 0x9b, 0x80, 0xd2, 0x64, 0x22,
	0x8b, 0x03, 0x9b, 0x9f, 0x97, 0x51, 0x63, 0xaf, 0x48, 0x48, 0x24, 0x01, 0x1f, 0x09, 0xdc, 0x44,
	0x35, 0xc6, 0xa7, 0xa0, 0xb4, 0x48, 0x42, 0x46, 0x1d, 0xab, 0x65, 0xb5, 0xab, 0x7d, 0x54, 0x4a,
	0x01, 0xc5, 0x29, 0x5a, 0xa1, 0x65, 0x44, 0x48, 0x28, 0x4d, 0x40, 0x29, 0x67, 0xae, 0x65, 0xb5,
	0xeb, 0xdd, 0x57, 0xbf, 0x2e, 0x9b, 0x9d, 0x31, 0xd3, 0x07, 0xe9, 0xd0, 0x8b, 0xc4, 0xc4, 0x54,
	0x60, 0x3e, 0x1d, 0x45, 0x0f, 0x7d, 0x3d, 0x93, 0xa0, 0xbc, 0xdd, 0x28, 0xda, 0x2d, 0x02, 0x2f,
	0x4e, 0x3b, 0xff, 0x9b, 0x3a, 0x8d, 0xd2, 0x9d, 0x69, 0x50, 0x7d, 0xfb, 0x06, 0x61, 0x64, 0xbc,
	0x81, 0x90, 0x14, 0x22, 0x0e, 0x19, 0xa7, 0x70, 0xe2, 0xcc, 0xe7, 0x69, 0x55, 0x33, 0x25, 0xc8,
	0x04, 0x2c, 0x51, 0x23, 0x16, 0xd1, 0x21, 0xd0, 0x90, 0x4c, 0x44, 0xca, 0xb5, 0xb3, 0xd0, 0xb2,
	0xda, 0xb5, 0x9d, 0x35, 0xcf, 0xdc, 0x9e, 0x39, 0xe4, 0x19, 0x87, 0xbc, 0x17, 0x82, 0xf1, 0xee,
	0x93, 0xb3, 0xcb, 0x66, 0xe5, 0xeb, 0x8f, 0x66, 0xfb, 0x1e, 0x09, 0x67, 0x01, 0xaa, 0x5f, 0x2f,
	0x08, 0xbb, 0x39, 0x00, 0x9f, 0xa0, 0x95, 0x63, 0xa6, 0x0f, 0x68, 0x42, 0x8e, 0x49, 0x5c, 0x52,
	0x17, 0x1f, 0x9e, 0x6a, 0xdf, 0x52, 0x0c, 0x79, 0x8a, 0x6c, 0xc6, 0x23, 0xe0, 0x9a, 0x4d, 0xa1,
	0x04, 0x2f, 0x3d, 0x3c, 0xf8, 0xbf, 0x1b, 0x88, 0xe1, 0x3e, 0x46, 0xd5, 0x98, 0xf1, 0x43, 0xa0,
	0x6f, 0x5e, 0x0e, 0x9c, 0x7f, 0x5a, 0xf3, 0x59, 0x07, 0x6e, 0x04, 0x1c, 0xa0, 0xba, 0x69, 0x5a,
	0x98, 0xdd, 0xe2, 0x2c, 0xb7, 0xac, 0xf6, 0xbf, 0x3b, 0x5b, 0xde, 0x9d, 0x01, 0xf7, 0xfe, 0x18,
	0x35, 0x6f, 0x6f, 0xbf, 0xf7, 0xf6, 0x5d, 0x30, 0x18, 0xbc, 0xef, 0xed, 0xf7, 0x6b, 0x26, 0x76,
	0x30, 0x93, 0x90, 0x15, 0x28, 0x81, 0x53, 0xc6, 0xc7, 0x21, 0xe3, 0x1a, 0x12, 0x50, 0xda, 0xa9,
	0xfe, 0x85, 0x02, 0x0d, 0x24, 0x30, 0x0c, 0xfc, 0x09, 0x6d, 0x68, 0xa1, 0x49, 0x1c, 0x4a, 0xc2,
	0x68, 0x18, 0xb3, 0xa3, 0x94, 0x51, 0xa2, 0x99, 0xe0, 0xa5, 0xcb, 0x28, 0x1b, 0xbb, 0xee, 0xf3,
	0x8c, 0xf4, 0xfd, 0xb2, 0xb9, 0x75, 0x0f, 0x52, 0xc0, 0xf5, 0xc5, 0x69, 0x07, 0x99, 0xac, 0x03,
	0xae, 0xfb, 0xeb, 0x39, 0xa2, 0x47, 0x18, 0x7d, 0x7d, 0x0b, 0x28, 0x1c, 0xde, 0x4c, 0x51, 0xed,
	0x8e, 0x29, 0xf8, 0xd1, 0xed, 0x88, 0x65, 0x6f, 0x82, 0x14, 0x8a, 0xc4, 0x76, 0x05, 0xaf, 0x22,
	0x5b, 0x27, 0x84, 0xab, 0x11, 0x24, 0x61, 0x02, 0x47, 0x29, 0x28, 0x6d, 0x5b, 0x78, 0x05, 0x35,
	0x4a, 0xff, 0xa3, 0x58, 0x28, 0xb0, 0xe7, 0x70, 0x15, 0x2d, 0xa6, 0x5c, 0x81, 0xb6, 0xe7, 0x71,
	0x03, 0x55, 0x65, 0x22, 0x22, 0x50, 0x0a, 0xa8, 0xbd, 0x80, 0xeb, 0x68, 0x99, 0x02, 0x89, 0xb2,
	0xe6, 0xda, 0x8b, 0xdd, 0xde, 0xd9, 0x95, 0x6b, 0x9d, 0x5f, 0xb9, 0xd6, 0xcf, 0x2b, 0xd7, 0xfa,
	0x72, 0xed, 0x56, 0xce, 0xaf, 0xdd, 0xca, 0xb7, 0x6b, 0xb7, 0xf2, 0xe1, 0xd9, 0x9d, 0x12, 0x4d,
	0x23, 0x3b, 0x23, 0xc6, 0x09, 0x8f, 0xa0, 0x5c, 0x87, 0x71, 0xe1, 0xa2, 0x7f, 0x92, 0x3f, 0x6f,
	0x79, 0xd9, 0xc3, 0xa5, 0xfc, 0x79, 0x79, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xd4, 0x1f,
	0x59, 0xfa, 0x04, 0x00, 0x00,
}

func (m *DepositorInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DepositorInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DepositorInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalPaidLiquidationAmount.Size()
		i -= size
		if _, err := m.TotalPaidLiquidationAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDeposit(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size, err := m.PendingInterest.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintDeposit(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if m.DepositType != 0 {
		i = encodeVarintDeposit(dAtA, i, uint64(m.DepositType))
		i--
		dAtA[i] = 0x40
	}
	if len(m.LinkedNFT) > 0 {
		for iNdEx := len(m.LinkedNFT) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.LinkedNFT[iNdEx])
			copy(dAtA[i:], m.LinkedNFT[iNdEx])
			i = encodeVarintDeposit(dAtA, i, uint64(len(m.LinkedNFT[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	{
		size, err := m.IncentiveAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintDeposit(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.WithdrawalAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintDeposit(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.LockedAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintDeposit(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.PoolIndex) > 0 {
		i -= len(m.PoolIndex)
		copy(dAtA[i:], m.PoolIndex)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.PoolIndex)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DepositorAddress) > 0 {
		i -= len(m.DepositorAddress)
		copy(dAtA[i:], m.DepositorAddress)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.DepositorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.InvestorId) > 0 {
		i -= len(m.InvestorId)
		copy(dAtA[i:], m.InvestorId)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.InvestorId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDeposit(dAtA []byte, offset int, v uint64) int {
	offset -= sovDeposit(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DepositorInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.InvestorId)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	l = len(m.DepositorAddress)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	l = len(m.PoolIndex)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	l = m.LockedAmount.Size()
	n += 1 + l + sovDeposit(uint64(l))
	l = m.WithdrawalAmount.Size()
	n += 1 + l + sovDeposit(uint64(l))
	l = m.IncentiveAmount.Size()
	n += 1 + l + sovDeposit(uint64(l))
	if len(m.LinkedNFT) > 0 {
		for _, s := range m.LinkedNFT {
			l = len(s)
			n += 1 + l + sovDeposit(uint64(l))
		}
	}
	if m.DepositType != 0 {
		n += 1 + sovDeposit(uint64(m.DepositType))
	}
	l = m.PendingInterest.Size()
	n += 1 + l + sovDeposit(uint64(l))
	l = m.TotalPaidLiquidationAmount.Size()
	n += 1 + l + sovDeposit(uint64(l))
	return n
}

func sovDeposit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDeposit(x uint64) (n int) {
	return sovDeposit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DepositorInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeposit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DepositorInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DepositorInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvestorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InvestorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositorAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositorAddress = append(m.DepositorAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.DepositorAddress == nil {
				m.DepositorAddress = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LockedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WithdrawalAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncentiveAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IncentiveAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LinkedNFT", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LinkedNFT = append(m.LinkedNFT, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositType", wireType)
			}
			m.DepositType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositType |= DepositorInfo_DEPOSITTYPE(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingInterest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PendingInterest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalPaidLiquidationAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalPaidLiquidationAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDeposit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeposit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDeposit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDeposit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDeposit
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDeposit
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDeposit
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDeposit        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDeposit          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDeposit = fmt.Errorf("proto: unexpected end of group")
)
