// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: joltify/spv/poolinfo.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PoolInfo_POOLSTATUS int32

const (
	PoolInfo_ACTIVE   PoolInfo_POOLSTATUS = 0
	PoolInfo_INACTIVE PoolInfo_POOLSTATUS = 1
	PoolInfo_CLOSED   PoolInfo_POOLSTATUS = 2
	PoolInfo_PREPARE  PoolInfo_POOLSTATUS = 3
	PoolInfo_CLOSING  PoolInfo_POOLSTATUS = 4
)

var PoolInfo_POOLSTATUS_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
	2: "CLOSED",
	3: "PREPARE",
	4: "CLOSING",
}

var PoolInfo_POOLSTATUS_value = map[string]int32{
	"ACTIVE":   0,
	"INACTIVE": 1,
	"CLOSED":   2,
	"PREPARE":  3,
	"CLOSING":  4,
}

func (x PoolInfo_POOLSTATUS) String() string {
	return proto.EnumName(PoolInfo_POOLSTATUS_name, int32(x))
}

func (PoolInfo_POOLSTATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_353391ba5ffe1b1b, []int{0, 0}
}

type PoolInfo_POOLTYPE int32

const (
	PoolInfo_JUNIOR PoolInfo_POOLTYPE = 0
	PoolInfo_SENIOR PoolInfo_POOLTYPE = 1
)

var PoolInfo_POOLTYPE_name = map[int32]string{
	0: "JUNIOR",
	1: "SENIOR",
}

var PoolInfo_POOLTYPE_value = map[string]int32{
	"JUNIOR": 0,
	"SENIOR": 1,
}

func (x PoolInfo_POOLTYPE) String() string {
	return proto.EnumName(PoolInfo_POOLTYPE_name, int32(x))
}

func (PoolInfo_POOLTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_353391ba5ffe1b1b, []int{0, 1}
}

type PoolInfo struct {
	Index         string                                        `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	PoolName      string                                        `protobuf:"bytes,2,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	LinkedProject int32                                         `protobuf:"varint,3,opt,name=linked_project,json=linkedProject,proto3" json:"linked_project,omitempty"`
	OwnerAddress  github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,4,opt,name=owner_address,json=ownerAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"owner_address,omitempty"`
	Apy           github_com_cosmos_cosmos_sdk_types.Dec        `protobuf:"bytes,5,opt,name=apy,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"apy"`
	TotalAmount   types.Coin                                    `protobuf:"bytes,6,opt,name=total_amount,json=totalAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_amount"`
	PayFreq       int32                                         `protobuf:"varint,7,opt,name=pay_freq,json=payFreq,proto3" json:"pay_freq,omitempty"`
	ReserveFactor github_com_cosmos_cosmos_sdk_types.Dec        `protobuf:"bytes,8,opt,name=reserve_factor,json=reserveFactor,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"reserve_factor"`
	//  string            pool_nFT_class      = 9 [
	//    (cosmos_proto.scalar)  = "cosmos.Class",
	//    (gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/x/nft.Class",
	//    (gogoproto.nullable)   = false
	//  ];
	PoolNFTIds             []string                                        `protobuf:"bytes,9,rep,name=pool_nFT_ids,json=poolNFTIds,proto3" json:"pool_nFT_ids,omitempty"`
	LastPaymentTime        time.Time                                       `protobuf:"bytes,10,opt,name=last_payment_time,json=lastPaymentTime,proto3,stdtime" json:"last_payment_time"`
	PoolStatus             PoolInfo_POOLSTATUS                             `protobuf:"varint,11,opt,name=pool_status,json=poolStatus,proto3,enum=joltify.spv.PoolInfo_POOLSTATUS" json:"pool_status,omitempty"`
	BorrowedAmount         types.Coin                                      `protobuf:"bytes,12,opt,name=borrowed_amount,json=borrowedAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"borrowed_amount"`
	PoolInterest           github_com_cosmos_cosmos_sdk_types.Dec          `protobuf:"bytes,13,opt,name=pool_interest,json=poolInterest,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"pool_interest"`
	ProjectLength          uint64                                          `protobuf:"varint,14,opt,name=project_length,json=projectLength,proto3" json:"project_length,omitempty"`
	BorrowableAmount       types.Coin                                      `protobuf:"bytes,15,opt,name=borrowable_amount,json=borrowableAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"borrowable_amount"`
	TargetAmount           types.Coin                                      `protobuf:"bytes,16,opt,name=target_amount,json=targetAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"target_amount"`
	PoolType               PoolInfo_POOLTYPE                               `protobuf:"varint,17,opt,name=pool_type,json=poolType,proto3,enum=joltify.spv.PoolInfo_POOLTYPE" json:"pool_type,omitempty"`
	EscrowInterestAmount   types.Coin                                      `protobuf:"bytes,18,opt,name=escrow_interest_amount,json=escrowInterestAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"escrow_interest_amount"`
	EscrowPrincipalAmount  types.Coin                                      `protobuf:"bytes,19,opt,name=escrow_principal_amount,json=escrowPrincipalAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"escrow_principal_amount"`
	WithdrawProposalAmount types.Coin                                      `protobuf:"bytes,20,opt,name=withdraw_proposal_amount,json=withdrawProposalAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"withdraw_proposal_amount"`
	ProjectDueTime         time.Time                                       `protobuf:"bytes,21,opt,name=project_due_time,json=projectDueTime,proto3,stdtime" json:"project_due_time"`
	WithdrawAccounts       []github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,22,rep,name=withdraw_accounts,json=withdrawAccounts,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"withdraw_accounts,omitempty"`
}

func (m *PoolInfo) Reset()         { *m = PoolInfo{} }
func (m *PoolInfo) String() string { return proto.CompactTextString(m) }
func (*PoolInfo) ProtoMessage()    {}
func (*PoolInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_353391ba5ffe1b1b, []int{0}
}
func (m *PoolInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolInfo.Merge(m, src)
}
func (m *PoolInfo) XXX_Size() int {
	return m.Size()
}
func (m *PoolInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PoolInfo proto.InternalMessageInfo

func (m *PoolInfo) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *PoolInfo) GetPoolName() string {
	if m != nil {
		return m.PoolName
	}
	return ""
}

func (m *PoolInfo) GetLinkedProject() int32 {
	if m != nil {
		return m.LinkedProject
	}
	return 0
}

func (m *PoolInfo) GetOwnerAddress() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *PoolInfo) GetTotalAmount() types.Coin {
	if m != nil {
		return m.TotalAmount
	}
	return types.Coin{}
}

func (m *PoolInfo) GetPayFreq() int32 {
	if m != nil {
		return m.PayFreq
	}
	return 0
}

func (m *PoolInfo) GetPoolNFTIds() []string {
	if m != nil {
		return m.PoolNFTIds
	}
	return nil
}

func (m *PoolInfo) GetLastPaymentTime() time.Time {
	if m != nil {
		return m.LastPaymentTime
	}
	return time.Time{}
}

func (m *PoolInfo) GetPoolStatus() PoolInfo_POOLSTATUS {
	if m != nil {
		return m.PoolStatus
	}
	return PoolInfo_ACTIVE
}

func (m *PoolInfo) GetBorrowedAmount() types.Coin {
	if m != nil {
		return m.BorrowedAmount
	}
	return types.Coin{}
}

func (m *PoolInfo) GetProjectLength() uint64 {
	if m != nil {
		return m.ProjectLength
	}
	return 0
}

func (m *PoolInfo) GetBorrowableAmount() types.Coin {
	if m != nil {
		return m.BorrowableAmount
	}
	return types.Coin{}
}

func (m *PoolInfo) GetTargetAmount() types.Coin {
	if m != nil {
		return m.TargetAmount
	}
	return types.Coin{}
}

func (m *PoolInfo) GetPoolType() PoolInfo_POOLTYPE {
	if m != nil {
		return m.PoolType
	}
	return PoolInfo_JUNIOR
}

func (m *PoolInfo) GetEscrowInterestAmount() types.Coin {
	if m != nil {
		return m.EscrowInterestAmount
	}
	return types.Coin{}
}

func (m *PoolInfo) GetEscrowPrincipalAmount() types.Coin {
	if m != nil {
		return m.EscrowPrincipalAmount
	}
	return types.Coin{}
}

func (m *PoolInfo) GetWithdrawProposalAmount() types.Coin {
	if m != nil {
		return m.WithdrawProposalAmount
	}
	return types.Coin{}
}

func (m *PoolInfo) GetProjectDueTime() time.Time {
	if m != nil {
		return m.ProjectDueTime
	}
	return time.Time{}
}

func (m *PoolInfo) GetWithdrawAccounts() []github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.WithdrawAccounts
	}
	return nil
}

type PoolWithInvestors struct {
	PoolIndex string   `protobuf:"bytes,1,opt,name=poolIndex,proto3" json:"poolIndex,omitempty"`
	Investors []string `protobuf:"bytes,2,rep,name=investors,proto3" json:"investors,omitempty"`
}

func (m *PoolWithInvestors) Reset()         { *m = PoolWithInvestors{} }
func (m *PoolWithInvestors) String() string { return proto.CompactTextString(m) }
func (*PoolWithInvestors) ProtoMessage()    {}
func (*PoolWithInvestors) Descriptor() ([]byte, []int) {
	return fileDescriptor_353391ba5ffe1b1b, []int{1}
}
func (m *PoolWithInvestors) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolWithInvestors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolWithInvestors.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolWithInvestors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolWithInvestors.Merge(m, src)
}
func (m *PoolWithInvestors) XXX_Size() int {
	return m.Size()
}
func (m *PoolWithInvestors) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolWithInvestors.DiscardUnknown(m)
}

var xxx_messageInfo_PoolWithInvestors proto.InternalMessageInfo

func (m *PoolWithInvestors) GetPoolIndex() string {
	if m != nil {
		return m.PoolIndex
	}
	return ""
}

func (m *PoolWithInvestors) GetInvestors() []string {
	if m != nil {
		return m.Investors
	}
	return nil
}

type PoolDepositedInvestors struct {
	PoolIndex     string                                          `protobuf:"bytes,1,opt,name=poolIndex,proto3" json:"poolIndex,omitempty"`
	WalletAddress []github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,4,rep,name=wallet_address,json=walletAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"wallet_address,omitempty"`
}

func (m *PoolDepositedInvestors) Reset()         { *m = PoolDepositedInvestors{} }
func (m *PoolDepositedInvestors) String() string { return proto.CompactTextString(m) }
func (*PoolDepositedInvestors) ProtoMessage()    {}
func (*PoolDepositedInvestors) Descriptor() ([]byte, []int) {
	return fileDescriptor_353391ba5ffe1b1b, []int{2}
}
func (m *PoolDepositedInvestors) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolDepositedInvestors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolDepositedInvestors.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolDepositedInvestors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolDepositedInvestors.Merge(m, src)
}
func (m *PoolDepositedInvestors) XXX_Size() int {
	return m.Size()
}
func (m *PoolDepositedInvestors) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolDepositedInvestors.DiscardUnknown(m)
}

var xxx_messageInfo_PoolDepositedInvestors proto.InternalMessageInfo

func (m *PoolDepositedInvestors) GetPoolIndex() string {
	if m != nil {
		return m.PoolIndex
	}
	return ""
}

func (m *PoolDepositedInvestors) GetWalletAddress() []github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.WalletAddress
	}
	return nil
}

type WalletsLinkPool struct {
	WalletAddress github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"wallet_address,omitempty"`
	PoolsIndex    []string                                      `protobuf:"bytes,2,rep,name=pools_index,json=poolsIndex,proto3" json:"pools_index,omitempty"`
}

func (m *WalletsLinkPool) Reset()         { *m = WalletsLinkPool{} }
func (m *WalletsLinkPool) String() string { return proto.CompactTextString(m) }
func (*WalletsLinkPool) ProtoMessage()    {}
func (*WalletsLinkPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_353391ba5ffe1b1b, []int{3}
}
func (m *WalletsLinkPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WalletsLinkPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WalletsLinkPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WalletsLinkPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletsLinkPool.Merge(m, src)
}
func (m *WalletsLinkPool) XXX_Size() int {
	return m.Size()
}
func (m *WalletsLinkPool) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletsLinkPool.DiscardUnknown(m)
}

var xxx_messageInfo_WalletsLinkPool proto.InternalMessageInfo

func (m *WalletsLinkPool) GetWalletAddress() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.WalletAddress
	}
	return nil
}

func (m *WalletsLinkPool) GetPoolsIndex() []string {
	if m != nil {
		return m.PoolsIndex
	}
	return nil
}

func init() {
	proto.RegisterEnum("joltify.spv.PoolInfo_POOLSTATUS", PoolInfo_POOLSTATUS_name, PoolInfo_POOLSTATUS_value)
	proto.RegisterEnum("joltify.spv.PoolInfo_POOLTYPE", PoolInfo_POOLTYPE_name, PoolInfo_POOLTYPE_value)
	proto.RegisterType((*PoolInfo)(nil), "joltify.spv.PoolInfo")
	proto.RegisterType((*PoolWithInvestors)(nil), "joltify.spv.PoolWithInvestors")
	proto.RegisterType((*PoolDepositedInvestors)(nil), "joltify.spv.PoolDepositedInvestors")
	proto.RegisterType((*WalletsLinkPool)(nil), "joltify.spv.WalletsLinkPool")
}

func init() { proto.RegisterFile("joltify/spv/poolinfo.proto", fileDescriptor_353391ba5ffe1b1b) }

var fileDescriptor_353391ba5ffe1b1b = []byte{
	// 1011 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6f, 0xe3, 0x44,
	0x14, 0x8f, 0xfb, 0x99, 0x4e, 0x3e, 0x9a, 0xce, 0x76, 0x8b, 0x5b, 0x50, 0x62, 0x45, 0x02, 0xe5,
	0x52, 0x9b, 0x5d, 0x24, 0x2e, 0x70, 0x49, 0x9a, 0x14, 0x82, 0xa2, 0xc4, 0x72, 0xb2, 0xac, 0xe0,
	0x62, 0x4d, 0xec, 0x49, 0xea, 0xad, 0xe3, 0xf1, 0x7a, 0x26, 0x49, 0x73, 0x44, 0x88, 0xfb, 0xfe,
	0x0f, 0x1c, 0x90, 0x38, 0xef, 0x99, 0xf3, 0x1e, 0x57, 0x7b, 0x42, 0x1c, 0xba, 0xa8, 0xfd, 0x2f,
	0x38, 0xa1, 0xf9, 0x70, 0x53, 0x24, 0x90, 0x8a, 0xe4, 0x93, 0x3d, 0xbf, 0x37, 0xf3, 0x7e, 0xbf,
	0x79, 0xef, 0xcd, 0x9b, 0x01, 0x27, 0x2f, 0x48, 0xc8, 0x82, 0xc9, 0xca, 0xa2, 0xf1, 0xc2, 0x8a,
	0x09, 0x09, 0x83, 0x68, 0x42, 0xcc, 0x38, 0x21, 0x8c, 0xc0, 0x82, 0xb2, 0x99, 0x34, 0x5e, 0x9c,
	0x1c, 0x7b, 0x84, 0xce, 0x08, 0x75, 0x85, 0xc9, 0x92, 0x03, 0x39, 0xef, 0xe4, 0x70, 0x4a, 0xa6,
	0x44, 0xe2, 0xfc, 0x4f, 0xa1, 0x55, 0x39, 0xc7, 0x1a, 0x23, 0x8a, 0xad, 0xc5, 0x93, 0x31, 0x66,
	0xe8, 0x89, 0xe5, 0x91, 0x20, 0x52, 0xf6, 0xda, 0x94, 0x90, 0x69, 0x88, 0x2d, 0x31, 0x1a, 0xcf,
	0x27, 0x16, 0x0b, 0x66, 0x98, 0x32, 0x34, 0x8b, 0xe5, 0x84, 0xfa, 0x6f, 0xfb, 0x20, 0x6f, 0x13,
	0x12, 0x76, 0xa3, 0x09, 0x81, 0x87, 0x60, 0x3b, 0x88, 0x7c, 0x7c, 0xa5, 0x6b, 0x86, 0xd6, 0xd8,
	0x73, 0xe4, 0x00, 0x7e, 0x08, 0xf6, 0xb8, 0x66, 0x37, 0x42, 0x33, 0xac, 0x6f, 0x08, 0x4b, 0x9e,
	0x03, 0x7d, 0x34, 0xc3, 0xf0, 0x63, 0x50, 0x0e, 0x83, 0xe8, 0x12, 0xfb, 0x5c, 0xf3, 0x0b, 0xec,
	0x31, 0x7d, 0xd3, 0xd0, 0x1a, 0xdb, 0x4e, 0x49, 0xa2, 0xb6, 0x04, 0xe1, 0x0c, 0x94, 0xc8, 0x32,
	0xc2, 0x89, 0x8b, 0x7c, 0x3f, 0xc1, 0x94, 0xea, 0x5b, 0x86, 0xd6, 0x28, 0xb6, 0xbe, 0xfe, 0xeb,
	0xba, 0x76, 0x3a, 0x0d, 0xd8, 0xc5, 0x7c, 0x6c, 0x7a, 0x64, 0xa6, 0x76, 0xac, 0x3e, 0xa7, 0xd4,
	0xbf, 0xb4, 0xd8, 0x2a, 0xc6, 0xd4, 0x6c, 0x7a, 0x5e, 0x53, 0x2e, 0x7c, 0xf7, 0xfa, 0xf4, 0x91,
	0x8a, 0x8b, 0x42, 0x5a, 0x2b, 0x86, 0xa9, 0x53, 0x14, 0xee, 0x15, 0x04, 0xfb, 0x60, 0x13, 0xc5,
	0x2b, 0x7d, 0x9b, 0x8b, 0x6d, 0x7d, 0xf9, 0xe6, 0xba, 0x96, 0xfb, 0xe3, 0xba, 0xf6, 0xc9, 0x03,
	0x88, 0xda, 0xd8, 0x7b, 0xf7, 0xfa, 0x14, 0x28, 0x86, 0x36, 0xf6, 0x1c, 0xee, 0x08, 0x46, 0xa0,
	0xc8, 0x08, 0x43, 0xa1, 0x8b, 0x66, 0x64, 0x1e, 0x31, 0x7d, 0xc7, 0xd0, 0x1a, 0x85, 0xa7, 0xc7,
	0xa6, 0x9a, 0xc7, 0xa3, 0x6f, 0xaa, 0xe8, 0x9b, 0x67, 0x24, 0x88, 0x5a, 0x9f, 0x72, 0xce, 0x5f,
	0xdf, 0xd7, 0x1a, 0x0f, 0xe0, 0xe4, 0x0b, 0xa8, 0x53, 0x10, 0x04, 0x4d, 0xe1, 0x1f, 0x1e, 0x83,
	0x7c, 0x8c, 0x56, 0xee, 0x24, 0xc1, 0x2f, 0xf5, 0x5d, 0x11, 0xcf, 0xdd, 0x18, 0xad, 0xce, 0x13,
	0xfc, 0x12, 0x7a, 0xa0, 0x9c, 0x60, 0x8a, 0x93, 0x05, 0x76, 0x27, 0xc8, 0x63, 0x24, 0xd1, 0xf3,
	0x19, 0xec, 0xb2, 0xa4, 0x7c, 0x9e, 0x0b, 0x97, 0xd0, 0x00, 0x45, 0x99, 0xf2, 0xf3, 0x91, 0x1b,
	0xf8, 0x54, 0xdf, 0x33, 0x36, 0x1b, 0x7b, 0x0e, 0x10, 0x59, 0x3f, 0x1f, 0x75, 0x7d, 0x0a, 0x6d,
	0x70, 0x10, 0x22, 0xca, 0xdc, 0x18, 0xad, 0x66, 0x38, 0x62, 0x2e, 0xaf, 0x2b, 0x1d, 0x88, 0xb0,
	0x9c, 0x98, 0xb2, 0xe8, 0xcc, 0xb4, 0xe8, 0xcc, 0x51, 0x5a, 0x74, 0xad, 0x3c, 0x57, 0xf9, 0xea,
	0x7d, 0x4d, 0x73, 0xf6, 0xf9, 0x72, 0x5b, 0xae, 0xe6, 0x76, 0xd8, 0x04, 0x05, 0xc1, 0x49, 0x19,
	0x62, 0x73, 0xaa, 0x17, 0x0c, 0xad, 0x51, 0x7e, 0x6a, 0x98, 0xf7, 0x8e, 0x87, 0x99, 0x16, 0xaa,
	0x69, 0x0f, 0x06, 0xbd, 0xe1, 0xa8, 0x39, 0x7a, 0x36, 0x94, 0xa2, 0x86, 0x62, 0x0d, 0x64, 0x60,
	0x7f, 0x4c, 0x92, 0x84, 0x2c, 0xb1, 0x9f, 0x66, 0xaa, 0x98, 0x7d, 0xa6, 0xca, 0x29, 0x87, 0x4a,
	0x16, 0x02, 0x25, 0x21, 0x3c, 0x88, 0x18, 0x4e, 0x30, 0x65, 0x7a, 0x29, 0x83, 0x84, 0x88, 0xf8,
	0x77, 0x95, 0x47, 0x7e, 0xca, 0xd4, 0xf1, 0x72, 0x43, 0x1c, 0x4d, 0xd9, 0x85, 0x5e, 0x36, 0xb4,
	0xc6, 0x96, 0x53, 0x52, 0x68, 0x4f, 0x80, 0xf0, 0x0a, 0x1c, 0x48, 0x6d, 0x68, 0x1c, 0xe2, 0x34,
	0x02, 0xfb, 0xd9, 0x47, 0xa0, 0xb2, 0x66, 0x51, 0x31, 0x88, 0x41, 0x89, 0xa1, 0x64, 0x8a, 0x59,
	0xca, 0x5a, 0xc9, 0x9e, 0xb5, 0x28, 0x19, 0x14, 0xe3, 0x17, 0xaa, 0x2b, 0xf1, 0x19, 0xfa, 0x81,
	0x28, 0x96, 0xea, 0x7f, 0x17, 0xcb, 0xe8, 0x3b, 0xbb, 0x23, 0xbb, 0xd6, 0x68, 0x15, 0x63, 0xf8,
	0x83, 0x06, 0x8e, 0x30, 0xf5, 0x12, 0xb2, 0xbc, 0xcb, 0x5a, 0x2a, 0x1c, 0x66, 0x2f, 0xfc, 0x50,
	0x52, 0xa5, 0xd9, 0x54, 0x1b, 0xf8, 0x51, 0x03, 0x1f, 0x28, 0x0d, 0x71, 0x12, 0x44, 0x5e, 0x10,
	0xaf, 0xfb, 0xcb, 0xa3, 0xec, 0x45, 0x3c, 0x96, 0x5c, 0x76, 0x4a, 0xa5, 0x54, 0xfc, 0xa4, 0x01,
	0x7d, 0x19, 0xb0, 0x0b, 0x3f, 0x41, 0x5c, 0x07, 0x89, 0x09, 0x5d, 0xcb, 0x38, 0xcc, 0x5e, 0xc6,
	0x51, 0x4a, 0x66, 0x2b, 0x2e, 0xa5, 0xa3, 0x0f, 0x2a, 0x69, 0x85, 0xfb, 0x73, 0x2c, 0xdb, 0xc9,
	0xe3, 0xff, 0xd1, 0x4e, 0xd2, 0xf3, 0xd1, 0x9e, 0x63, 0xd1, 0x4d, 0xe6, 0xe0, 0xe0, 0x6e, 0x5b,
	0xc8, 0xf3, 0x38, 0x07, 0xd5, 0x8f, 0x8c, 0xcd, 0x4c, 0x2f, 0x9d, 0x4a, 0x4a, 0xd1, 0x54, 0x0c,
	0xf5, 0x1e, 0x00, 0xeb, 0xde, 0x04, 0x01, 0xd8, 0x69, 0x9e, 0x8d, 0xba, 0xdf, 0x76, 0x2a, 0x39,
	0x58, 0x04, 0xf9, 0x6e, 0x5f, 0x8d, 0x34, 0x6e, 0x39, 0xeb, 0x0d, 0x86, 0x9d, 0x76, 0x65, 0x03,
	0x16, 0xc0, 0xae, 0xed, 0x74, 0xec, 0xa6, 0xd3, 0xa9, 0x6c, 0xf2, 0x01, 0x37, 0x74, 0xfb, 0x5f,
	0x55, 0xb6, 0xea, 0x75, 0x90, 0x4f, 0x8b, 0x97, 0xaf, 0xf8, 0xe6, 0x59, 0xbf, 0x3b, 0x70, 0x2a,
	0x39, 0xfe, 0x3f, 0xec, 0x88, 0x7f, 0xad, 0x3e, 0x00, 0x07, 0xbc, 0xd2, 0x9f, 0x07, 0xec, 0xa2,
	0x1b, 0x2d, 0x30, 0x65, 0x24, 0xa1, 0xf0, 0x23, 0x79, 0x38, 0xba, 0xf7, 0x2e, 0xf3, 0x35, 0xc0,
	0xad, 0x41, 0x3a, 0x55, 0xdf, 0x10, 0xad, 0x7d, 0x0d, 0xd4, 0x7f, 0xd1, 0xc0, 0x11, 0xf7, 0xd8,
	0xc6, 0x31, 0xa1, 0x01, 0xc3, 0xfe, 0x43, 0xdd, 0x12, 0x50, 0x5e, 0xa2, 0x30, 0xe4, 0x3d, 0xe0,
	0xee, 0x92, 0xcf, 0x36, 0xde, 0x25, 0xe9, 0x5f, 0x61, 0xf5, 0x9f, 0x35, 0xb0, 0xff, 0x5c, 0x20,
	0xb4, 0x17, 0x44, 0x97, 0x5c, 0xf4, 0xbf, 0x88, 0xd0, 0x32, 0x7e, 0x69, 0xfc, 0x53, 0x04, 0xac,
	0xc9, 0x6b, 0x8b, 0xba, 0xf2, 0xe5, 0xb4, 0xb1, 0xbe, 0x29, 0xa9, 0x08, 0x4b, 0xcb, 0x7e, 0x73,
	0x53, 0xd5, 0xde, 0xde, 0x54, 0xb5, 0x3f, 0x6f, 0xaa, 0xda, 0xab, 0xdb, 0x6a, 0xee, 0xed, 0x6d,
	0x35, 0xf7, 0xfb, 0x6d, 0x35, 0xf7, 0xfd, 0xe7, 0xf7, 0xf4, 0xa8, 0xce, 0x75, 0x3a, 0x09, 0x22,
	0x14, 0x79, 0x38, 0x1d, 0xf3, 0x76, 0xef, 0x07, 0xd1, 0xd4, 0xba, 0x12, 0x6f, 0x47, 0xa1, 0x71,
	0xbc, 0x23, 0x4e, 0xc2, 0x67, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xae, 0x8d, 0xc6, 0x57,
	0x0a, 0x00, 0x00,
}

func (m *PoolInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WithdrawAccounts) > 0 {
		for iNdEx := len(m.WithdrawAccounts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WithdrawAccounts[iNdEx])
			copy(dAtA[i:], m.WithdrawAccounts[iNdEx])
			i = encodeVarintPoolinfo(dAtA, i, uint64(len(m.WithdrawAccounts[iNdEx])))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xb2
		}
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.ProjectDueTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.ProjectDueTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintPoolinfo(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xaa
	{
		size, err := m.WithdrawProposalAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPoolinfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xa2
	{
		size, err := m.EscrowPrincipalAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPoolinfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x9a
	{
		size, err := m.EscrowInterestAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPoolinfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x92
	if m.PoolType != 0 {
		i = encodeVarintPoolinfo(dAtA, i, uint64(m.PoolType))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	{
		size, err := m.TargetAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPoolinfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x82
	{
		size, err := m.BorrowableAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPoolinfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x7a
	if m.ProjectLength != 0 {
		i = encodeVarintPoolinfo(dAtA, i, uint64(m.ProjectLength))
		i--
		dAtA[i] = 0x70
	}
	{
		size := m.PoolInterest.Size()
		i -= size
		if _, err := m.PoolInterest.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPoolinfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	{
		size, err := m.BorrowedAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPoolinfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if m.PoolStatus != 0 {
		i = encodeVarintPoolinfo(dAtA, i, uint64(m.PoolStatus))
		i--
		dAtA[i] = 0x58
	}
	n8, err8 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.LastPaymentTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.LastPaymentTime):])
	if err8 != nil {
		return 0, err8
	}
	i -= n8
	i = encodeVarintPoolinfo(dAtA, i, uint64(n8))
	i--
	dAtA[i] = 0x52
	if len(m.PoolNFTIds) > 0 {
		for iNdEx := len(m.PoolNFTIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PoolNFTIds[iNdEx])
			copy(dAtA[i:], m.PoolNFTIds[iNdEx])
			i = encodeVarintPoolinfo(dAtA, i, uint64(len(m.PoolNFTIds[iNdEx])))
			i--
			dAtA[i] = 0x4a
		}
	}
	{
		size := m.ReserveFactor.Size()
		i -= size
		if _, err := m.ReserveFactor.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPoolinfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.PayFreq != 0 {
		i = encodeVarintPoolinfo(dAtA, i, uint64(m.PayFreq))
		i--
		dAtA[i] = 0x38
	}
	{
		size, err := m.TotalAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPoolinfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.Apy.Size()
		i -= size
		if _, err := m.Apy.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPoolinfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintPoolinfo(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0x22
	}
	if m.LinkedProject != 0 {
		i = encodeVarintPoolinfo(dAtA, i, uint64(m.LinkedProject))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PoolName) > 0 {
		i -= len(m.PoolName)
		copy(dAtA[i:], m.PoolName)
		i = encodeVarintPoolinfo(dAtA, i, uint64(len(m.PoolName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintPoolinfo(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PoolWithInvestors) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolWithInvestors) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolWithInvestors) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Investors) > 0 {
		for iNdEx := len(m.Investors) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Investors[iNdEx])
			copy(dAtA[i:], m.Investors[iNdEx])
			i = encodeVarintPoolinfo(dAtA, i, uint64(len(m.Investors[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.PoolIndex) > 0 {
		i -= len(m.PoolIndex)
		copy(dAtA[i:], m.PoolIndex)
		i = encodeVarintPoolinfo(dAtA, i, uint64(len(m.PoolIndex)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PoolDepositedInvestors) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolDepositedInvestors) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolDepositedInvestors) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WalletAddress) > 0 {
		for iNdEx := len(m.WalletAddress) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WalletAddress[iNdEx])
			copy(dAtA[i:], m.WalletAddress[iNdEx])
			i = encodeVarintPoolinfo(dAtA, i, uint64(len(m.WalletAddress[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.PoolIndex) > 0 {
		i -= len(m.PoolIndex)
		copy(dAtA[i:], m.PoolIndex)
		i = encodeVarintPoolinfo(dAtA, i, uint64(len(m.PoolIndex)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WalletsLinkPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WalletsLinkPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WalletsLinkPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PoolsIndex) > 0 {
		for iNdEx := len(m.PoolsIndex) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PoolsIndex[iNdEx])
			copy(dAtA[i:], m.PoolsIndex[iNdEx])
			i = encodeVarintPoolinfo(dAtA, i, uint64(len(m.PoolsIndex[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.WalletAddress) > 0 {
		i -= len(m.WalletAddress)
		copy(dAtA[i:], m.WalletAddress)
		i = encodeVarintPoolinfo(dAtA, i, uint64(len(m.WalletAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPoolinfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovPoolinfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PoolInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovPoolinfo(uint64(l))
	}
	l = len(m.PoolName)
	if l > 0 {
		n += 1 + l + sovPoolinfo(uint64(l))
	}
	if m.LinkedProject != 0 {
		n += 1 + sovPoolinfo(uint64(m.LinkedProject))
	}
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovPoolinfo(uint64(l))
	}
	l = m.Apy.Size()
	n += 1 + l + sovPoolinfo(uint64(l))
	l = m.TotalAmount.Size()
	n += 1 + l + sovPoolinfo(uint64(l))
	if m.PayFreq != 0 {
		n += 1 + sovPoolinfo(uint64(m.PayFreq))
	}
	l = m.ReserveFactor.Size()
	n += 1 + l + sovPoolinfo(uint64(l))
	if len(m.PoolNFTIds) > 0 {
		for _, s := range m.PoolNFTIds {
			l = len(s)
			n += 1 + l + sovPoolinfo(uint64(l))
		}
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.LastPaymentTime)
	n += 1 + l + sovPoolinfo(uint64(l))
	if m.PoolStatus != 0 {
		n += 1 + sovPoolinfo(uint64(m.PoolStatus))
	}
	l = m.BorrowedAmount.Size()
	n += 1 + l + sovPoolinfo(uint64(l))
	l = m.PoolInterest.Size()
	n += 1 + l + sovPoolinfo(uint64(l))
	if m.ProjectLength != 0 {
		n += 1 + sovPoolinfo(uint64(m.ProjectLength))
	}
	l = m.BorrowableAmount.Size()
	n += 1 + l + sovPoolinfo(uint64(l))
	l = m.TargetAmount.Size()
	n += 2 + l + sovPoolinfo(uint64(l))
	if m.PoolType != 0 {
		n += 2 + sovPoolinfo(uint64(m.PoolType))
	}
	l = m.EscrowInterestAmount.Size()
	n += 2 + l + sovPoolinfo(uint64(l))
	l = m.EscrowPrincipalAmount.Size()
	n += 2 + l + sovPoolinfo(uint64(l))
	l = m.WithdrawProposalAmount.Size()
	n += 2 + l + sovPoolinfo(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.ProjectDueTime)
	n += 2 + l + sovPoolinfo(uint64(l))
	if len(m.WithdrawAccounts) > 0 {
		for _, b := range m.WithdrawAccounts {
			l = len(b)
			n += 2 + l + sovPoolinfo(uint64(l))
		}
	}
	return n
}

func (m *PoolWithInvestors) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolIndex)
	if l > 0 {
		n += 1 + l + sovPoolinfo(uint64(l))
	}
	if len(m.Investors) > 0 {
		for _, s := range m.Investors {
			l = len(s)
			n += 1 + l + sovPoolinfo(uint64(l))
		}
	}
	return n
}

func (m *PoolDepositedInvestors) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolIndex)
	if l > 0 {
		n += 1 + l + sovPoolinfo(uint64(l))
	}
	if len(m.WalletAddress) > 0 {
		for _, b := range m.WalletAddress {
			l = len(b)
			n += 1 + l + sovPoolinfo(uint64(l))
		}
	}
	return n
}

func (m *WalletsLinkPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WalletAddress)
	if l > 0 {
		n += 1 + l + sovPoolinfo(uint64(l))
	}
	if len(m.PoolsIndex) > 0 {
		for _, s := range m.PoolsIndex {
			l = len(s)
			n += 1 + l + sovPoolinfo(uint64(l))
		}
	}
	return n
}

func sovPoolinfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPoolinfo(x uint64) (n int) {
	return sovPoolinfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PoolInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LinkedProject", wireType)
			}
			m.LinkedProject = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LinkedProject |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = append(m.OwnerAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.OwnerAddress == nil {
				m.OwnerAddress = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Apy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Apy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayFreq", wireType)
			}
			m.PayFreq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PayFreq |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReserveFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolNFTIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolNFTIds = append(m.PoolNFTIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPaymentTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.LastPaymentTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolStatus", wireType)
			}
			m.PoolStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolStatus |= PoolInfo_POOLSTATUS(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowedAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BorrowedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolInterest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PoolInterest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectLength", wireType)
			}
			m.ProjectLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectLength |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowableAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BorrowableAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TargetAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolType", wireType)
			}
			m.PoolType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolType |= PoolInfo_POOLTYPE(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowInterestAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EscrowInterestAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowPrincipalAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EscrowPrincipalAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawProposalAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WithdrawProposalAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectDueTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.ProjectDueTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawAccounts", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawAccounts = append(m.WithdrawAccounts, make([]byte, postIndex-iNdEx))
			copy(m.WithdrawAccounts[len(m.WithdrawAccounts)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoolWithInvestors) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolWithInvestors: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolWithInvestors: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Investors", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Investors = append(m.Investors, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoolDepositedInvestors) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolDepositedInvestors: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolDepositedInvestors: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WalletAddress = append(m.WalletAddress, make([]byte, postIndex-iNdEx))
			copy(m.WalletAddress[len(m.WalletAddress)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WalletsLinkPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WalletsLinkPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WalletsLinkPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WalletAddress = append(m.WalletAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.WalletAddress == nil {
				m.WalletAddress = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolsIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolsIndex = append(m.PoolsIndex, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoolinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPoolinfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPoolinfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolinfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPoolinfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPoolinfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPoolinfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPoolinfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPoolinfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPoolinfo = fmt.Errorf("proto: unexpected end of group")
)
