// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: joltify/spv/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ad7ca650742ee34, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ad7ca650742ee34, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryListPoolsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListPoolsRequest) Reset()         { *m = QueryListPoolsRequest{} }
func (m *QueryListPoolsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListPoolsRequest) ProtoMessage()    {}
func (*QueryListPoolsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ad7ca650742ee34, []int{2}
}
func (m *QueryListPoolsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListPoolsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListPoolsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListPoolsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListPoolsRequest.Merge(m, src)
}
func (m *QueryListPoolsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListPoolsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListPoolsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListPoolsRequest proto.InternalMessageInfo

func (m *QueryListPoolsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListPoolsResponse struct {
	PoolsInfo  []*PoolInfo         `protobuf:"bytes,1,rep,name=pools_info,json=poolsInfo,proto3" json:"pools_info,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListPoolsResponse) Reset()         { *m = QueryListPoolsResponse{} }
func (m *QueryListPoolsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListPoolsResponse) ProtoMessage()    {}
func (*QueryListPoolsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ad7ca650742ee34, []int{3}
}
func (m *QueryListPoolsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListPoolsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListPoolsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListPoolsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListPoolsResponse.Merge(m, src)
}
func (m *QueryListPoolsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListPoolsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListPoolsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListPoolsResponse proto.InternalMessageInfo

func (m *QueryListPoolsResponse) GetPoolsInfo() []*PoolInfo {
	if m != nil {
		return m.PoolsInfo
	}
	return nil
}

func (m *QueryListPoolsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryQueryPoolRequest struct {
	PoolIndex string `protobuf:"bytes,1,opt,name=poolIndex,proto3" json:"poolIndex,omitempty"`
}

func (m *QueryQueryPoolRequest) Reset()         { *m = QueryQueryPoolRequest{} }
func (m *QueryQueryPoolRequest) String() string { return proto.CompactTextString(m) }
func (*QueryQueryPoolRequest) ProtoMessage()    {}
func (*QueryQueryPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ad7ca650742ee34, []int{4}
}
func (m *QueryQueryPoolRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryQueryPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryQueryPoolRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryQueryPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryQueryPoolRequest.Merge(m, src)
}
func (m *QueryQueryPoolRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryQueryPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryQueryPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryQueryPoolRequest proto.InternalMessageInfo

func (m *QueryQueryPoolRequest) GetPoolIndex() string {
	if m != nil {
		return m.PoolIndex
	}
	return ""
}

type QueryQueryPoolResponse struct {
	PoolInfo *PoolInfo `protobuf:"bytes,1,opt,name=pool_info,json=poolInfo,proto3" json:"pool_info,omitempty"`
}

func (m *QueryQueryPoolResponse) Reset()         { *m = QueryQueryPoolResponse{} }
func (m *QueryQueryPoolResponse) String() string { return proto.CompactTextString(m) }
func (*QueryQueryPoolResponse) ProtoMessage()    {}
func (*QueryQueryPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ad7ca650742ee34, []int{5}
}
func (m *QueryQueryPoolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryQueryPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryQueryPoolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryQueryPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryQueryPoolResponse.Merge(m, src)
}
func (m *QueryQueryPoolResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryQueryPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryQueryPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryQueryPoolResponse proto.InternalMessageInfo

func (m *QueryQueryPoolResponse) GetPoolInfo() *PoolInfo {
	if m != nil {
		return m.PoolInfo
	}
	return nil
}

type QueryDepositorRequest struct {
	WalletAddress    string `protobuf:"bytes,1,opt,name=walletAddress,proto3" json:"walletAddress,omitempty"`
	DepositPoolIndex string `protobuf:"bytes,2,opt,name=depositPoolIndex,proto3" json:"depositPoolIndex,omitempty"`
}

func (m *QueryDepositorRequest) Reset()         { *m = QueryDepositorRequest{} }
func (m *QueryDepositorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDepositorRequest) ProtoMessage()    {}
func (*QueryDepositorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ad7ca650742ee34, []int{6}
}
func (m *QueryDepositorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDepositorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDepositorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDepositorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDepositorRequest.Merge(m, src)
}
func (m *QueryDepositorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDepositorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDepositorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDepositorRequest proto.InternalMessageInfo

func (m *QueryDepositorRequest) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

func (m *QueryDepositorRequest) GetDepositPoolIndex() string {
	if m != nil {
		return m.DepositPoolIndex
	}
	return ""
}

type QueryDepositorResponse struct {
	Depositor *DepositorInfo `protobuf:"bytes,1,opt,name=depositor,proto3" json:"depositor,omitempty"`
}

func (m *QueryDepositorResponse) Reset()         { *m = QueryDepositorResponse{} }
func (m *QueryDepositorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDepositorResponse) ProtoMessage()    {}
func (*QueryDepositorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ad7ca650742ee34, []int{7}
}
func (m *QueryDepositorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDepositorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDepositorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDepositorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDepositorResponse.Merge(m, src)
}
func (m *QueryDepositorResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDepositorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDepositorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDepositorResponse proto.InternalMessageInfo

func (m *QueryDepositorResponse) GetDepositor() *DepositorInfo {
	if m != nil {
		return m.Depositor
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "joltify.spv.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "joltify.spv.QueryParamsResponse")
	proto.RegisterType((*QueryListPoolsRequest)(nil), "joltify.spv.QueryListPoolsRequest")
	proto.RegisterType((*QueryListPoolsResponse)(nil), "joltify.spv.QueryListPoolsResponse")
	proto.RegisterType((*QueryQueryPoolRequest)(nil), "joltify.spv.QueryQueryPoolRequest")
	proto.RegisterType((*QueryQueryPoolResponse)(nil), "joltify.spv.QueryQueryPoolResponse")
	proto.RegisterType((*QueryDepositorRequest)(nil), "joltify.spv.QueryDepositorRequest")
	proto.RegisterType((*QueryDepositorResponse)(nil), "joltify.spv.QueryDepositorResponse")
}

func init() { proto.RegisterFile("joltify/spv/query.proto", fileDescriptor_4ad7ca650742ee34) }

var fileDescriptor_4ad7ca650742ee34 = []byte{
	// 633 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0xe3, 0xf6, 0xf7, 0xab, 0xf0, 0x56, 0x48, 0x68, 0xfb, 0x3f, 0xad, 0xdc, 0xca, 0x85,
	0x52, 0x15, 0xe1, 0x55, 0x53, 0x15, 0x89, 0x23, 0x15, 0x02, 0x2a, 0x81, 0x14, 0xc2, 0x8d, 0x4b,
	0xe4, 0xc4, 0x1b, 0x77, 0x91, 0xb3, 0xe3, 0x7a, 0x37, 0xa1, 0x51, 0xd5, 0x03, 0x88, 0x07, 0x40,
	0xe2, 0xc2, 0x23, 0xf5, 0x58, 0x89, 0x0b, 0x27, 0x84, 0x12, 0xde, 0x80, 0x17, 0x40, 0xd9, 0x5d,
	0xbb, 0x76, 0x1c, 0xca, 0x2d, 0x99, 0x9d, 0x99, 0xef, 0x67, 0x66, 0xbf, 0x5e, 0xb4, 0xf2, 0x0e,
	0x22, 0xc9, 0x3a, 0x03, 0x22, 0xe2, 0x3e, 0x39, 0xed, 0xd1, 0x64, 0xe0, 0xc5, 0x09, 0x48, 0xc0,
	0xf3, 0xe6, 0xc0, 0x13, 0x71, 0xbf, 0xba, 0x18, 0x42, 0x08, 0x2a, 0x4e, 0xc6, 0xbf, 0x74, 0x4a,
	0x75, 0x23, 0x04, 0x08, 0x23, 0x4a, 0xfc, 0x98, 0x11, 0x9f, 0x73, 0x90, 0xbe, 0x64, 0xc0, 0x85,
	0x39, 0xdd, 0x6b, 0x83, 0xe8, 0x82, 0x20, 0x2d, 0x5f, 0x50, 0xdd, 0x99, 0xf4, 0xf7, 0x5b, 0x54,
	0xfa, 0xfb, 0x24, 0xf6, 0x43, 0xc6, 0x55, 0xb2, 0xc9, 0xad, 0xe6, 0x29, 0x62, 0x80, 0x88, 0xf1,
	0x4e, 0xaa, 0xb2, 0x96, 0x3f, 0x0b, 0x68, 0x0c, 0x82, 0x49, 0x73, 0xb4, 0x5a, 0x28, 0xf3, 0x13,
	0xbf, 0x6b, 0xc4, 0xdd, 0x45, 0x84, 0x5f, 0x8f, 0x25, 0xeb, 0x2a, 0xd8, 0xa0, 0xa7, 0x3d, 0x2a,
	0xa4, 0xfb, 0x02, 0x2d, 0x14, 0xa2, 0x22, 0x06, 0x2e, 0x28, 0xde, 0x47, 0x73, 0xba, 0x78, 0xd5,
	0xda, 0xb2, 0x76, 0xe7, 0x6b, 0x0b, 0x5e, 0x6e, 0x76, 0x4f, 0x27, 0x1f, 0xfd, 0x77, 0xf9, 0x63,
	0xb3, 0xd2, 0x30, 0x89, 0x6e, 0x13, 0x2d, 0xa9, 0x4e, 0x2f, 0x99, 0x90, 0x75, 0x80, 0x28, 0x95,
	0xc0, 0xcf, 0x10, 0xba, 0x9e, 0xce, 0xf4, 0xdb, 0xf1, 0xf4, 0x2a, 0xbc, 0xf1, 0x2a, 0x3c, 0xbd,
	0x64, 0xb3, 0x0a, 0xaf, 0xee, 0x87, 0xd4, 0xd4, 0x36, 0x72, 0x95, 0xee, 0x57, 0x0b, 0x2d, 0x4f,
	0x2a, 0x18, 0xdc, 0x43, 0x84, 0xc6, 0x2b, 0x12, 0xcd, 0xf1, 0x92, 0x56, 0xad, 0xad, 0xd9, 0xdd,
	0xf9, 0xda, 0x72, 0x11, 0x19, 0x20, 0x52, 0xa7, 0x0d, 0x5b, 0x65, 0x1e, 0xf3, 0x0e, 0xe0, 0xe7,
	0x05, 0xb2, 0x19, 0x45, 0x76, 0xff, 0x9f, 0x64, 0x5a, 0xb3, 0x80, 0x76, 0x68, 0x66, 0xd7, 0xab,
	0x04, 0x88, 0xd2, 0xd9, 0x37, 0x90, 0x92, 0x3b, 0xe6, 0x01, 0x3d, 0x53, 0xa3, 0xdb, 0x8d, 0xeb,
	0x80, 0xfb, 0xca, 0x0c, 0x94, 0x2b, 0x33, 0x03, 0x1d, 0xe8, 0xba, 0x74, 0x1e, 0xeb, 0x86, 0x79,
	0x6e, 0xe9, 0x7e, 0x1d, 0x70, 0x99, 0xa1, 0x78, 0xaa, 0x1d, 0x01, 0x49, 0x4a, 0x71, 0x17, 0xdd,
	0x7e, 0xef, 0x47, 0x11, 0x95, 0x4f, 0x82, 0x20, 0xa1, 0x42, 0x18, 0x92, 0x62, 0x10, 0xef, 0xa1,
	0x3b, 0xc6, 0x4b, 0xf5, 0x0c, 0x79, 0x46, 0x25, 0x96, 0xe2, 0xee, 0x1b, 0x43, 0x9e, 0x93, 0x32,
	0xe4, 0x8f, 0x91, 0x1d, 0xa4, 0x41, 0x43, 0xbe, 0x5e, 0x20, 0xcf, 0x4a, 0xcc, 0x75, 0x64, 0xd9,
	0xb5, 0xdf, 0xb3, 0xe8, 0x7f, 0xd5, 0x15, 0x9f, 0xa0, 0x39, 0xed, 0x31, 0xbc, 0x59, 0xa8, 0x2d,
	0x1b, 0xb8, 0xba, 0xf5, 0xf7, 0x04, 0x4d, 0xe4, 0xae, 0x7f, 0xfc, 0xf6, 0xeb, 0xcb, 0xcc, 0x12,
	0x5e, 0x20, 0xe5, 0x6f, 0x03, 0xf7, 0x90, 0x9d, 0xd9, 0x09, 0xbb, 0xe5, 0x5e, 0x93, 0x6e, 0xae,
	0x6e, 0xdf, 0x98, 0x63, 0x24, 0x37, 0x95, 0xe4, 0x1a, 0x5e, 0x29, 0x48, 0x46, 0x4c, 0xc8, 0xa6,
	0x72, 0x1f, 0xfe, 0x60, 0x21, 0x3b, 0xbb, 0xf5, 0x69, 0xba, 0x93, 0x4e, 0x9a, 0xa6, 0x5b, 0xb2,
	0x8d, 0xfb, 0x40, 0xe9, 0xde, 0xc3, 0xdb, 0xa4, 0xf4, 0x86, 0x29, 0x61, 0x72, 0x9e, 0x99, 0xef,
	0x02, 0x7f, 0xb2, 0x90, 0x9d, 0x5d, 0xc6, 0x34, 0x86, 0x49, 0x1f, 0x4d, 0x63, 0x28, 0x19, 0xc0,
	0xf5, 0x14, 0xc3, 0x2e, 0xde, 0x21, 0x53, 0x5e, 0x29, 0x48, 0xc8, 0x79, 0xc1, 0x75, 0x17, 0x47,
	0xf5, 0xcb, 0xa1, 0x63, 0x5d, 0x0d, 0x1d, 0xeb, 0xe7, 0xd0, 0xb1, 0x3e, 0x8f, 0x9c, 0xca, 0xd5,
	0xc8, 0xa9, 0x7c, 0x1f, 0x39, 0x95, 0xb7, 0x8f, 0x42, 0x26, 0x4f, 0x7a, 0x2d, 0xaf, 0x0d, 0xdd,
	0xb4, 0xd7, 0xc3, 0x0e, 0xe3, 0x3e, 0x6f, 0xd3, 0xf4, 0x7f, 0x33, 0xa2, 0x3c, 0x60, 0x3c, 0x24,
	0x67, 0x4a, 0x45, 0x0e, 0x62, 0x2a, 0x5a, 0x73, 0xea, 0xc1, 0x3b, 0xf8, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x53, 0xf9, 0x17, 0x9a, 0xc9, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Listpools items.
	ListPools(ctx context.Context, in *QueryListPoolsRequest, opts ...grpc.CallOption) (*QueryListPoolsResponse, error)
	// Queries a list of QueryPool items.
	QueryPool(ctx context.Context, in *QueryQueryPoolRequest, opts ...grpc.CallOption) (*QueryQueryPoolResponse, error)
	Depositor(ctx context.Context, in *QueryDepositorRequest, opts ...grpc.CallOption) (*QueryDepositorResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/joltify.spv.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListPools(ctx context.Context, in *QueryListPoolsRequest, opts ...grpc.CallOption) (*QueryListPoolsResponse, error) {
	out := new(QueryListPoolsResponse)
	err := c.cc.Invoke(ctx, "/joltify.spv.Query/ListPools", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryPool(ctx context.Context, in *QueryQueryPoolRequest, opts ...grpc.CallOption) (*QueryQueryPoolResponse, error) {
	out := new(QueryQueryPoolResponse)
	err := c.cc.Invoke(ctx, "/joltify.spv.Query/QueryPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Depositor(ctx context.Context, in *QueryDepositorRequest, opts ...grpc.CallOption) (*QueryDepositorResponse, error) {
	out := new(QueryDepositorResponse)
	err := c.cc.Invoke(ctx, "/joltify.spv.Query/Depositor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Listpools items.
	ListPools(context.Context, *QueryListPoolsRequest) (*QueryListPoolsResponse, error)
	// Queries a list of QueryPool items.
	QueryPool(context.Context, *QueryQueryPoolRequest) (*QueryQueryPoolResponse, error)
	Depositor(context.Context, *QueryDepositorRequest) (*QueryDepositorResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ListPools(ctx context.Context, req *QueryListPoolsRequest) (*QueryListPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPools not implemented")
}
func (*UnimplementedQueryServer) QueryPool(ctx context.Context, req *QueryQueryPoolRequest) (*QueryQueryPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPool not implemented")
}
func (*UnimplementedQueryServer) Depositor(ctx context.Context, req *QueryDepositorRequest) (*QueryDepositorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Depositor not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/joltify.spv.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/joltify.spv.Query/ListPools",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListPools(ctx, req.(*QueryListPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryQueryPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/joltify.spv.Query/QueryPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryPool(ctx, req.(*QueryQueryPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Depositor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDepositorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Depositor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/joltify.spv.Query/Depositor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Depositor(ctx, req.(*QueryDepositorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "joltify.spv.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ListPools",
			Handler:    _Query_ListPools_Handler,
		},
		{
			MethodName: "QueryPool",
			Handler:    _Query_QueryPool_Handler,
		},
		{
			MethodName: "Depositor",
			Handler:    _Query_Depositor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "joltify/spv/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryListPoolsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListPoolsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListPoolsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListPoolsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListPoolsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListPoolsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PoolsInfo) > 0 {
		for iNdEx := len(m.PoolsInfo) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PoolsInfo[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryQueryPoolRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryQueryPoolRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryQueryPoolRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PoolIndex) > 0 {
		i -= len(m.PoolIndex)
		copy(dAtA[i:], m.PoolIndex)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PoolIndex)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryQueryPoolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryQueryPoolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryQueryPoolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PoolInfo != nil {
		{
			size, err := m.PoolInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDepositorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDepositorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDepositorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DepositPoolIndex) > 0 {
		i -= len(m.DepositPoolIndex)
		copy(dAtA[i:], m.DepositPoolIndex)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DepositPoolIndex)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.WalletAddress) > 0 {
		i -= len(m.WalletAddress)
		copy(dAtA[i:], m.WalletAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.WalletAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDepositorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDepositorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDepositorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Depositor != nil {
		{
			size, err := m.Depositor.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryListPoolsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListPoolsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PoolsInfo) > 0 {
		for _, e := range m.PoolsInfo {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryQueryPoolRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolIndex)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryQueryPoolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolInfo != nil {
		l = m.PoolInfo.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDepositorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WalletAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.DepositPoolIndex)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDepositorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Depositor != nil {
		l = m.Depositor.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListPoolsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListPoolsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListPoolsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListPoolsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListPoolsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListPoolsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolsInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolsInfo = append(m.PoolsInfo, &PoolInfo{})
			if err := m.PoolsInfo[len(m.PoolsInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryQueryPoolRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryQueryPoolRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryQueryPoolRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryQueryPoolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryQueryPoolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryQueryPoolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PoolInfo == nil {
				m.PoolInfo = &PoolInfo{}
			}
			if err := m.PoolInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDepositorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDepositorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDepositorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WalletAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositPoolIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositPoolIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDepositorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDepositorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDepositorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depositor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Depositor == nil {
				m.Depositor = &DepositorInfo{}
			}
			if err := m.Depositor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
