// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: joltify/third_party/dydxprotocol/revshare/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MarketMappeRevenueShareParams represents params for the above message
type MarketMapperRevenueShareParams struct {
	// The address which will receive the revenue share payouts
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// The fraction of the fees which will go to the above mentioned address.
	// In parts-per-million
	RevenueSharePpm uint32 `protobuf:"varint,2,opt,name=revenue_share_ppm,json=revenueSharePpm,proto3" json:"revenue_share_ppm,omitempty"`
	// This parameter defines how many days post market initiation will the
	// revenue share be applied for. After valid_days from market initiation
	// the revenue share goes down to 0
	ValidDays uint32 `protobuf:"varint,3,opt,name=valid_days,json=validDays,proto3" json:"valid_days,omitempty"`
}

func (m *MarketMapperRevenueShareParams) Reset()         { *m = MarketMapperRevenueShareParams{} }
func (m *MarketMapperRevenueShareParams) String() string { return proto.CompactTextString(m) }
func (*MarketMapperRevenueShareParams) ProtoMessage()    {}
func (*MarketMapperRevenueShareParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_606ca5a5a4cf7f63, []int{0}
}
func (m *MarketMapperRevenueShareParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MarketMapperRevenueShareParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MarketMapperRevenueShareParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MarketMapperRevenueShareParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketMapperRevenueShareParams.Merge(m, src)
}
func (m *MarketMapperRevenueShareParams) XXX_Size() int {
	return m.Size()
}
func (m *MarketMapperRevenueShareParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketMapperRevenueShareParams.DiscardUnknown(m)
}

var xxx_messageInfo_MarketMapperRevenueShareParams proto.InternalMessageInfo

func (m *MarketMapperRevenueShareParams) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MarketMapperRevenueShareParams) GetRevenueSharePpm() uint32 {
	if m != nil {
		return m.RevenueSharePpm
	}
	return 0
}

func (m *MarketMapperRevenueShareParams) GetValidDays() uint32 {
	if m != nil {
		return m.ValidDays
	}
	return 0
}

func init() {
	proto.RegisterType((*MarketMapperRevenueShareParams)(nil), "joltify.third_party.dydxprotocol.revshare.MarketMapperRevenueShareParams")
}

func init() {
	proto.RegisterFile("joltify/third_party/dydxprotocol/revshare/params.proto", fileDescriptor_606ca5a5a4cf7f63)
}

var fileDescriptor_606ca5a5a4cf7f63 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0x2b, 0x31,
	0x14, 0x86, 0x9b, 0x7b, 0x41, 0x69, 0x40, 0xc4, 0xc1, 0xc5, 0x28, 0x18, 0x8a, 0xab, 0x2a, 0x74,
	0x02, 0x0a, 0xee, 0x2d, 0x2e, 0x2d, 0x48, 0xbb, 0x73, 0x13, 0xd2, 0x49, 0xda, 0x46, 0x67, 0x92,
	0x70, 0x92, 0x96, 0xe6, 0x2d, 0x7c, 0x03, 0x5f, 0xc2, 0x87, 0x70, 0x59, 0x5c, 0xb9, 0x94, 0xf6,
	0x45, 0xa4, 0x99, 0x19, 0x9c, 0xe5, 0xc9, 0x7f, 0xbe, 0xff, 0x84, 0x0f, 0xdf, 0xbd, 0x98, 0xc2,
	0xab, 0x59, 0xa0, 0x7e, 0xa1, 0x40, 0x30, 0xcb, 0xc1, 0x07, 0x2a, 0x82, 0x58, 0x5b, 0x30, 0xde,
	0xe4, 0xa6, 0xa0, 0x20, 0x57, 0x6e, 0xc1, 0x41, 0x52, 0xcb, 0x81, 0x97, 0x2e, 0x8b, 0x41, 0x72,
	0x55, 0x73, 0x59, 0x8b, 0xcb, 0xda, 0x5c, 0xd6, 0x70, 0xe7, 0x67, 0xb9, 0x71, 0xa5, 0x71, 0x2c,
	0x26, 0xb4, 0x1a, 0xaa, 0x96, 0xcb, 0x77, 0x84, 0xc9, 0x88, 0xc3, 0xab, 0xf4, 0x23, 0x6e, 0xad,
	0x84, 0xb1, 0x5c, 0x49, 0xbd, 0x94, 0x93, 0x3d, 0xf7, 0x14, 0xcf, 0x25, 0x37, 0xf8, 0x90, 0x0b,
	0x01, 0xd2, 0xb9, 0x14, 0xf5, 0x50, 0xbf, 0x3b, 0x4c, 0xbf, 0x3e, 0x06, 0xa7, 0x75, 0xcb, 0x7d,
	0x95, 0x4c, 0x3c, 0x28, 0x3d, 0x1f, 0x37, 0x8b, 0xc9, 0x35, 0x3e, 0x81, 0xaa, 0x89, 0xc5, 0x2f,
	0x30, 0x6b, 0xcb, 0xf4, 0x5f, 0x0f, 0xf5, 0x8f, 0xc6, 0xc7, 0xd0, 0x3e, 0x61, 0xcb, 0xe4, 0x02,
	0xe3, 0x15, 0x2f, 0x94, 0x60, 0x82, 0x07, 0x97, 0xfe, 0x8f, 0x4b, 0xdd, 0xf8, 0xf2, 0xc0, 0x83,
	0x1b, 0xce, 0x3e, 0xb7, 0x04, 0x6d, 0xb6, 0x04, 0xfd, 0x6c, 0x09, 0x7a, 0xdb, 0x91, 0xce, 0x66,
	0x47, 0x3a, 0xdf, 0x3b, 0xd2, 0x79, 0x7e, 0x9c, 0x2b, 0xbf, 0x58, 0x4e, 0xb3, 0xdc, 0x94, 0xb4,
	0x96, 0x31, 0x98, 0x29, 0xcd, 0x75, 0x2e, 0x9b, 0x99, 0x15, 0x52, 0x0b, 0xa5, 0xe7, 0x74, 0xdd,
	0xd6, 0xcb, 0xf6, 0x9a, 0xfe, 0xb4, 0xfa, 0x60, 0xa5, 0x9b, 0x1e, 0x44, 0x21, 0xb7, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x38, 0x31, 0x56, 0xa5, 0x90, 0x01, 0x00, 0x00,
}

func (m *MarketMapperRevenueShareParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MarketMapperRevenueShareParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MarketMapperRevenueShareParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidDays != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ValidDays))
		i--
		dAtA[i] = 0x18
	}
	if m.RevenueSharePpm != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RevenueSharePpm))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MarketMapperRevenueShareParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.RevenueSharePpm != 0 {
		n += 1 + sovParams(uint64(m.RevenueSharePpm))
	}
	if m.ValidDays != 0 {
		n += 1 + sovParams(uint64(m.ValidDays))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MarketMapperRevenueShareParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MarketMapperRevenueShareParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MarketMapperRevenueShareParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevenueSharePpm", wireType)
			}
			m.RevenueSharePpm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevenueSharePpm |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidDays", wireType)
			}
			m.ValidDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidDays |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
