// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: joltify/kyc/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BasicInfo struct {
	Description      string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	ProjectsUrl      string `protobuf:"bytes,2,opt,name=projects_url,json=projectsUrl,proto3" json:"projects_url,omitempty"`
	ProjectCountry   string `protobuf:"bytes,3,opt,name=project_country,json=projectCountry,proto3" json:"project_country,omitempty"`
	BusinessNumber   string `protobuf:"bytes,4,opt,name=business_number,json=businessNumber,proto3" json:"business_number,omitempty"`
	Reserved         []byte `protobuf:"bytes,5,opt,name=reserved,proto3" json:"reserved,omitempty"`
	ProjectName      string `protobuf:"bytes,6,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Email            string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Name             string `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	ProjectLogo      string `protobuf:"bytes,9,opt,name=project_logo,json=projectLogo,proto3" json:"project_logo,omitempty"`
	ProjectBrief     string `protobuf:"bytes,10,opt,name=project_brief,json=projectBrief,proto3" json:"project_brief,omitempty"`
	ExecutiveSummary string `protobuf:"bytes,11,opt,name=executive_summary,json=executiveSummary,proto3" json:"executive_summary,omitempty"`
}

func (m *BasicInfo) Reset()         { *m = BasicInfo{} }
func (m *BasicInfo) String() string { return proto.CompactTextString(m) }
func (*BasicInfo) ProtoMessage()    {}
func (*BasicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d397e055e79ddcb0, []int{0}
}
func (m *BasicInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BasicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BasicInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BasicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicInfo.Merge(m, src)
}
func (m *BasicInfo) XXX_Size() int {
	return m.Size()
}
func (m *BasicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BasicInfo proto.InternalMessageInfo

func (m *BasicInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BasicInfo) GetProjectsUrl() string {
	if m != nil {
		return m.ProjectsUrl
	}
	return ""
}

func (m *BasicInfo) GetProjectCountry() string {
	if m != nil {
		return m.ProjectCountry
	}
	return ""
}

func (m *BasicInfo) GetBusinessNumber() string {
	if m != nil {
		return m.BusinessNumber
	}
	return ""
}

func (m *BasicInfo) GetReserved() []byte {
	if m != nil {
		return m.Reserved
	}
	return nil
}

func (m *BasicInfo) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *BasicInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *BasicInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BasicInfo) GetProjectLogo() string {
	if m != nil {
		return m.ProjectLogo
	}
	return ""
}

func (m *BasicInfo) GetProjectBrief() string {
	if m != nil {
		return m.ProjectBrief
	}
	return ""
}

func (m *BasicInfo) GetExecutiveSummary() string {
	if m != nil {
		return m.ExecutiveSummary
	}
	return ""
}

// Market defines an asset in the pricefeed.
type ProjectInfo struct {
	Index                        int32                                         `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	SPVName                      string                                        `protobuf:"bytes,2,opt,name=SPV_name,json=SPVName,proto3" json:"SPV_name,omitempty"`
	BasicInfo                    *BasicInfo                                    `protobuf:"bytes,3,opt,name=basic_info,json=basicInfo,proto3" json:"basic_info,omitempty"`
	ProjectOwner                 github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,4,opt,name=project_owner,json=projectOwner,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"project_owner,omitempty"`
	ProjectLength                uint64                                        `protobuf:"varint,5,opt,name=project_length,json=projectLength,proto3" json:"project_length,omitempty"`
	SeparatePool                 bool                                          `protobuf:"varint,6,opt,name=separate_pool,json=separatePool,proto3" json:"separate_pool,omitempty"`
	BaseApy                      github_com_cosmos_cosmos_sdk_types.Dec        `protobuf:"bytes,7,opt,name=base_apy,json=baseApy,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"base_apy"`
	PayFreq                      string                                        `protobuf:"bytes,8,opt,name=pay_freq,json=payFreq,proto3" json:"pay_freq,omitempty"`
	WithdrawRequestWindowSeconds int32                                         `protobuf:"varint,9,opt,name=withdraw_request_window_seconds,json=withdrawRequestWindowSeconds,proto3" json:"withdraw_request_window_seconds,omitempty"`
	PoolLockedSeconds            int32                                         `protobuf:"varint,10,opt,name=pool_locked_seconds,json=poolLockedSeconds,proto3" json:"pool_locked_seconds,omitempty"`
	PoolTotalBorrowLimit         int32                                         `protobuf:"varint,11,opt,name=pool_total_borrow_limit,json=poolTotalBorrowLimit,proto3" json:"pool_total_borrow_limit,omitempty"`
	GraceTime                    time.Duration                                 `protobuf:"bytes,12,opt,name=grace_time,json=graceTime,proto3,stdduration" json:"grace_time"`
	MarketId                     string                                        `protobuf:"bytes,13,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	JuniorMinRatio               github_com_cosmos_cosmos_sdk_types.Dec        `protobuf:"bytes,14,opt,name=junior_min_ratio,json=juniorMinRatio,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"junior_min_ratio"`
	MinBorrowAmount              github_com_cosmos_cosmos_sdk_types.Int        `protobuf:"bytes,15,opt,name=min_borrow_amount,json=minBorrowAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"min_borrow_amount"`
	MinDepositAmount             github_com_cosmos_cosmos_sdk_types.Int        `protobuf:"bytes,16,opt,name=min_deposit_amount,json=minDepositAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"min_deposit_amount"`
}

func (m *ProjectInfo) Reset()         { *m = ProjectInfo{} }
func (m *ProjectInfo) String() string { return proto.CompactTextString(m) }
func (*ProjectInfo) ProtoMessage()    {}
func (*ProjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d397e055e79ddcb0, []int{1}
}
func (m *ProjectInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProjectInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectInfo.Merge(m, src)
}
func (m *ProjectInfo) XXX_Size() int {
	return m.Size()
}
func (m *ProjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectInfo proto.InternalMessageInfo

func (m *ProjectInfo) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ProjectInfo) GetSPVName() string {
	if m != nil {
		return m.SPVName
	}
	return ""
}

func (m *ProjectInfo) GetBasicInfo() *BasicInfo {
	if m != nil {
		return m.BasicInfo
	}
	return nil
}

func (m *ProjectInfo) GetProjectOwner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.ProjectOwner
	}
	return nil
}

func (m *ProjectInfo) GetProjectLength() uint64 {
	if m != nil {
		return m.ProjectLength
	}
	return 0
}

func (m *ProjectInfo) GetSeparatePool() bool {
	if m != nil {
		return m.SeparatePool
	}
	return false
}

func (m *ProjectInfo) GetPayFreq() string {
	if m != nil {
		return m.PayFreq
	}
	return ""
}

func (m *ProjectInfo) GetWithdrawRequestWindowSeconds() int32 {
	if m != nil {
		return m.WithdrawRequestWindowSeconds
	}
	return 0
}

func (m *ProjectInfo) GetPoolLockedSeconds() int32 {
	if m != nil {
		return m.PoolLockedSeconds
	}
	return 0
}

func (m *ProjectInfo) GetPoolTotalBorrowLimit() int32 {
	if m != nil {
		return m.PoolTotalBorrowLimit
	}
	return 0
}

func (m *ProjectInfo) GetGraceTime() time.Duration {
	if m != nil {
		return m.GraceTime
	}
	return 0
}

func (m *ProjectInfo) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

type Projects struct {
	Items []*ProjectInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (m *Projects) Reset()         { *m = Projects{} }
func (m *Projects) String() string { return proto.CompactTextString(m) }
func (*Projects) ProtoMessage()    {}
func (*Projects) Descriptor() ([]byte, []int) {
	return fileDescriptor_d397e055e79ddcb0, []int{2}
}
func (m *Projects) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Projects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Projects.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Projects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Projects.Merge(m, src)
}
func (m *Projects) XXX_Size() int {
	return m.Size()
}
func (m *Projects) XXX_DiscardUnknown() {
	xxx_messageInfo_Projects.DiscardUnknown(m)
}

var xxx_messageInfo_Projects proto.InternalMessageInfo

func (m *Projects) GetItems() []*ProjectInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

// Params defines the parameters for the module.
type Params struct {
	ProjectInfo string                                          `protobuf:"bytes,1,opt,name=project_info,json=projectInfo,proto3" json:"project_info,omitempty"`
	Submitter   []github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,2,rep,name=submitter,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"submitter,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_d397e055e79ddcb0, []int{3}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetProjectInfo() string {
	if m != nil {
		return m.ProjectInfo
	}
	return ""
}

func (m *Params) GetSubmitter() []github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Submitter
	}
	return nil
}

func init() {
	proto.RegisterType((*BasicInfo)(nil), "joltify.kyc.BasicInfo")
	proto.RegisterType((*ProjectInfo)(nil), "joltify.kyc.ProjectInfo")
	proto.RegisterType((*Projects)(nil), "joltify.kyc.Projects")
	proto.RegisterType((*Params)(nil), "joltify.kyc.Params")
}

func init() { proto.RegisterFile("joltify/kyc/params.proto", fileDescriptor_d397e055e79ddcb0) }

var fileDescriptor_d397e055e79ddcb0 = []byte{
	// 929 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcb, 0x6e, 0x24, 0x35,
	0x17, 0x4e, 0x4d, 0xd2, 0x49, 0xb7, 0x3b, 0x93, 0x8b, 0x27, 0xfa, 0xff, 0x4a, 0x40, 0x9d, 0x10,
	0x04, 0x44, 0x42, 0xa9, 0xd2, 0x0c, 0x1a, 0x16, 0x88, 0x4d, 0x9a, 0x80, 0x88, 0x14, 0x86, 0x56,
	0x65, 0x98, 0x91, 0xd8, 0x58, 0x75, 0x39, 0x5d, 0x71, 0x52, 0xb6, 0x2b, 0xb6, 0x2b, 0x9d, 0xda,
	0xf1, 0x08, 0x48, 0x6c, 0x78, 0x90, 0x79, 0x88, 0x59, 0x8e, 0x66, 0x85, 0x58, 0x04, 0x94, 0x3c,
	0x01, 0x5b, 0x56, 0xc8, 0x76, 0x55, 0x4f, 0x67, 0x07, 0x52, 0x56, 0xdd, 0xe7, 0xfb, 0x3e, 0x9f,
	0x63, 0x9f, 0x5b, 0x21, 0xff, 0x4c, 0x14, 0x9a, 0x8e, 0xeb, 0xf0, 0xbc, 0x4e, 0xc3, 0x32, 0x96,
	0x31, 0x53, 0x41, 0x29, 0x85, 0x16, 0xb8, 0xdf, 0x30, 0xc1, 0x79, 0x9d, 0x6e, 0x6d, 0xe4, 0x22,
	0x17, 0x16, 0x0f, 0xcd, 0x3f, 0x27, 0xd9, 0xda, 0x4c, 0x85, 0x62, 0x42, 0x11, 0x47, 0x38, 0xa3,
	0xa1, 0x06, 0xce, 0x0a, 0x93, 0x58, 0x41, 0x78, 0xf9, 0x38, 0x01, 0x1d, 0x3f, 0x0e, 0x53, 0x41,
	0x79, 0xcb, 0xe7, 0x42, 0xe4, 0x05, 0x84, 0xd6, 0x4a, 0xaa, 0x71, 0x98, 0x55, 0x32, 0xd6, 0x54,
	0x34, 0xfc, 0xee, 0x4f, 0xf3, 0xa8, 0x37, 0x8c, 0x15, 0x4d, 0x8f, 0xf8, 0x58, 0xe0, 0x1d, 0xd4,
	0xcf, 0x40, 0xa5, 0x92, 0x96, 0x46, 0xe2, 0x7b, 0x3b, 0xde, 0x5e, 0x2f, 0x9a, 0x85, 0xf0, 0x07,
	0x68, 0xb9, 0x94, 0xe2, 0x0c, 0x52, 0xad, 0x48, 0x25, 0x0b, 0xff, 0x81, 0x93, 0xb4, 0xd8, 0x0f,
	0xb2, 0xc0, 0x9f, 0xa0, 0xd5, 0xc6, 0x24, 0xa9, 0xa8, 0xb8, 0x96, 0xb5, 0x3f, 0x6f, 0x55, 0x2b,
	0x0d, 0xfc, 0x95, 0x43, 0x8d, 0x30, 0xa9, 0x14, 0xe5, 0xa0, 0x14, 0xe1, 0x15, 0x4b, 0x40, 0xfa,
	0x0b, 0x4e, 0xd8, 0xc2, 0xcf, 0x2c, 0x8a, 0xb7, 0x50, 0x57, 0x82, 0x02, 0x79, 0x09, 0x99, 0xdf,
	0xd9, 0xf1, 0xf6, 0x96, 0xa3, 0xa9, 0x3d, 0x73, 0x21, 0xc2, 0x63, 0x06, 0xfe, 0xe2, 0x9d, 0x0b,
	0x3d, 0x8b, 0x19, 0xe0, 0x0d, 0xd4, 0x01, 0x16, 0xd3, 0xc2, 0x5f, 0xb2, 0x9c, 0x33, 0x30, 0x46,
	0x0b, 0xf6, 0x40, 0xd7, 0x82, 0xf6, 0xff, 0xac, 0xb3, 0x42, 0xe4, 0xc2, 0xef, 0xdd, 0x71, 0x76,
	0x2c, 0x72, 0x81, 0x3f, 0x44, 0x0f, 0x5b, 0x49, 0x22, 0x29, 0x8c, 0x7d, 0x64, 0x35, 0xed, 0xb9,
	0xa1, 0xc1, 0xf0, 0xa7, 0x68, 0x1d, 0xae, 0x20, 0xad, 0x34, 0xbd, 0x04, 0xa2, 0x2a, 0xc6, 0x62,
	0x59, 0xfb, 0x7d, 0x2b, 0x5c, 0x9b, 0x12, 0x27, 0x0e, 0xdf, 0xfd, 0x6b, 0x09, 0xf5, 0x47, 0xee,
	0xb4, 0x2d, 0xc2, 0x06, 0xea, 0x50, 0x9e, 0xc1, 0x95, 0x4d, 0x7f, 0x27, 0x72, 0x06, 0xde, 0x44,
	0xdd, 0x93, 0xd1, 0x0b, 0xf7, 0x46, 0x97, 0xf4, 0xa5, 0x93, 0xd1, 0x0b, 0xfb, 0xbe, 0xa7, 0x08,
	0x25, 0xa6, 0x84, 0x84, 0xf2, 0xb1, 0xb0, 0xb9, 0xee, 0x3f, 0xf9, 0x5f, 0x30, 0xd3, 0x56, 0xc1,
	0xb4, 0xc2, 0x51, 0x2f, 0x99, 0x16, 0x9b, 0xbd, 0x7b, 0x89, 0x98, 0xf0, 0x26, 0xf9, 0xcb, 0xc3,
	0x6f, 0xff, 0xbe, 0xde, 0xde, 0xcf, 0xa9, 0x3e, 0xad, 0x92, 0x20, 0x15, 0xac, 0x69, 0xb7, 0xe6,
	0x67, 0x5f, 0x65, 0xe7, 0xa1, 0xae, 0x4b, 0x50, 0xc1, 0x41, 0x9a, 0x1e, 0x64, 0x99, 0x04, 0xa5,
	0xde, 0xbe, 0xda, 0x7f, 0xd4, 0x34, 0x65, 0x83, 0x0c, 0x6b, 0x0d, 0x6a, 0x9a, 0x93, 0xef, 0x8d,
	0x77, 0xfc, 0x11, 0x5a, 0x99, 0xe6, 0x16, 0x78, 0xae, 0x4f, 0x6d, 0x29, 0x17, 0xa2, 0xf6, 0x12,
	0xc7, 0x16, 0x34, 0xf9, 0x55, 0x60, 0x06, 0x44, 0x03, 0x29, 0x85, 0x28, 0x6c, 0x41, 0xbb, 0xd1,
	0x72, 0x0b, 0x8e, 0x84, 0x28, 0xf0, 0x4b, 0xd4, 0x35, 0x0d, 0x4f, 0xe2, 0xb2, 0x76, 0x45, 0x1d,
	0x7e, 0xf9, 0xfa, 0x7a, 0x7b, 0xee, 0xf7, 0xeb, 0xed, 0x8f, 0xff, 0xc5, 0xcd, 0x0f, 0x21, 0x7d,
	0xfb, 0x6a, 0x1f, 0x35, 0x57, 0x3e, 0x84, 0x34, 0x5a, 0x32, 0xde, 0x0e, 0xca, 0xda, 0x64, 0xb9,
	0x8c, 0x6b, 0x32, 0x96, 0x70, 0xd1, 0x34, 0xc6, 0x52, 0x19, 0xd7, 0xdf, 0x48, 0xb8, 0xc0, 0x5f,
	0xa3, 0xed, 0x09, 0xd5, 0xa7, 0x99, 0x8c, 0x27, 0x44, 0xc2, 0x45, 0x05, 0x4a, 0x93, 0x09, 0xe5,
	0x99, 0x98, 0x10, 0x05, 0xa9, 0xe0, 0x99, 0xb2, 0xed, 0xd2, 0x89, 0xde, 0x6f, 0x65, 0x91, 0x53,
	0xbd, 0xb4, 0xa2, 0x13, 0xa7, 0xc1, 0x01, 0x7a, 0x64, 0x9e, 0x45, 0x0a, 0x91, 0x9e, 0x43, 0x36,
	0x3d, 0x8a, 0xec, 0xd1, 0x75, 0x43, 0x1d, 0x5b, 0xa6, 0xd5, 0x3f, 0x45, 0xff, 0xb7, 0x7a, 0x2d,
	0x74, 0x5c, 0x90, 0x44, 0x48, 0x29, 0x26, 0xa4, 0xa0, 0x8c, 0x6a, 0xdb, 0x50, 0x9d, 0x68, 0xc3,
	0xd0, 0xcf, 0x0d, 0x3b, 0xb4, 0xe4, 0xb1, 0xe1, 0xf0, 0x10, 0xa1, 0x5c, 0xc6, 0x29, 0x10, 0x4d,
	0x19, 0xf8, 0xcb, 0xb6, 0x27, 0x36, 0x03, 0xb7, 0x0c, 0x82, 0x76, 0x19, 0x04, 0x87, 0xcd, 0x32,
	0x18, 0x76, 0x4d, 0xfa, 0x7e, 0xfd, 0x63, 0xdb, 0x8b, 0x7a, 0xf6, 0xd8, 0x73, 0xca, 0x00, 0xbf,
	0x87, 0x7a, 0x2c, 0x96, 0xe7, 0xa0, 0x09, 0xcd, 0xfc, 0x87, 0x36, 0x1b, 0x5d, 0x07, 0x1c, 0x65,
	0x78, 0x8c, 0xd6, 0xce, 0x2a, 0x4e, 0x85, 0x24, 0x8c, 0x72, 0x62, 0xdd, 0xf8, 0x2b, 0xf7, 0x50,
	0x8a, 0x15, 0xe7, 0xf5, 0x3b, 0xca, 0x23, 0xe3, 0x13, 0x9f, 0xa2, 0x75, 0x13, 0xa0, 0x79, 0x78,
	0xcc, 0xcc, 0xee, 0xf0, 0x57, 0xff, 0x73, 0xa0, 0x23, 0xae, 0x67, 0x02, 0x1d, 0x71, 0x1d, 0xad,
	0x32, 0xca, 0x5d, 0xc6, 0x0e, 0xac, 0x53, 0x7c, 0x86, 0xb0, 0x89, 0x94, 0x41, 0x29, 0x14, 0xd5,
	0x6d, 0xa8, 0xb5, 0x7b, 0x08, 0xb5, 0xc6, 0x28, 0x3f, 0x74, 0x6e, 0x5d, 0xac, 0xdd, 0x2f, 0x50,
	0xb7, 0x19, 0x79, 0xd3, 0x11, 0x1d, 0xaa, 0x81, 0x29, 0xdf, 0xdb, 0x99, 0xdf, 0xeb, 0x3f, 0xf1,
	0xef, 0x4c, 0xee, 0xcc, 0x62, 0x88, 0x9c, 0x6c, 0xf7, 0x17, 0x0f, 0x2d, 0x8e, 0xec, 0x17, 0x64,
	0x76, 0x5f, 0xd9, 0xd9, 0xf7, 0xee, 0xec, 0x2b, 0x3b, 0xe5, 0x63, 0xd4, 0x53, 0x55, 0xc2, 0xa8,
	0xd6, 0x20, 0xfd, 0x07, 0x3b, 0xf3, 0xf7, 0x3a, 0xe1, 0xef, 0x5c, 0x0f, 0x47, 0xaf, 0x6f, 0x06,
	0xde, 0x9b, 0x9b, 0x81, 0xf7, 0xe7, 0xcd, 0xc0, 0xfb, 0xf9, 0x76, 0x30, 0xf7, 0xe6, 0x76, 0x30,
	0xf7, 0xdb, 0xed, 0x60, 0xee, 0xc7, 0xcf, 0x67, 0x42, 0x35, 0x4f, 0xdb, 0x1f, 0x53, 0x1e, 0xf3,
	0x14, 0x5a, 0xdb, 0x6c, 0x84, 0x8c, 0xf2, 0x3c, 0xbc, 0xb2, 0xdf, 0x47, 0x1b, 0x3e, 0x59, 0xb4,
	0x6d, 0xfa, 0xd9, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x19, 0xcc, 0x0c, 0x22, 0x3b, 0x07, 0x00,
	0x00,
}

func (m *BasicInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BasicInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BasicInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExecutiveSummary) > 0 {
		i -= len(m.ExecutiveSummary)
		copy(dAtA[i:], m.ExecutiveSummary)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ExecutiveSummary)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.ProjectBrief) > 0 {
		i -= len(m.ProjectBrief)
		copy(dAtA[i:], m.ProjectBrief)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ProjectBrief)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.ProjectLogo) > 0 {
		i -= len(m.ProjectLogo)
		copy(dAtA[i:], m.ProjectLogo)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ProjectLogo)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Email) > 0 {
		i -= len(m.Email)
		copy(dAtA[i:], m.Email)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Email)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ProjectName) > 0 {
		i -= len(m.ProjectName)
		copy(dAtA[i:], m.ProjectName)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ProjectName)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Reserved) > 0 {
		i -= len(m.Reserved)
		copy(dAtA[i:], m.Reserved)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Reserved)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.BusinessNumber) > 0 {
		i -= len(m.BusinessNumber)
		copy(dAtA[i:], m.BusinessNumber)
		i = encodeVarintParams(dAtA, i, uint64(len(m.BusinessNumber)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ProjectCountry) > 0 {
		i -= len(m.ProjectCountry)
		copy(dAtA[i:], m.ProjectCountry)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ProjectCountry)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ProjectsUrl) > 0 {
		i -= len(m.ProjectsUrl)
		copy(dAtA[i:], m.ProjectsUrl)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ProjectsUrl)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProjectInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProjectInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProjectInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MinDepositAmount.Size()
		i -= size
		if _, err := m.MinDepositAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x82
	{
		size := m.MinBorrowAmount.Size()
		i -= size
		if _, err := m.MinBorrowAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x7a
	{
		size := m.JuniorMinRatio.Size()
		i -= size
		if _, err := m.JuniorMinRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x72
	if len(m.MarketId) > 0 {
		i -= len(m.MarketId)
		copy(dAtA[i:], m.MarketId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MarketId)))
		i--
		dAtA[i] = 0x6a
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.GraceTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.GraceTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x62
	if m.PoolTotalBorrowLimit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PoolTotalBorrowLimit))
		i--
		dAtA[i] = 0x58
	}
	if m.PoolLockedSeconds != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PoolLockedSeconds))
		i--
		dAtA[i] = 0x50
	}
	if m.WithdrawRequestWindowSeconds != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.WithdrawRequestWindowSeconds))
		i--
		dAtA[i] = 0x48
	}
	if len(m.PayFreq) > 0 {
		i -= len(m.PayFreq)
		copy(dAtA[i:], m.PayFreq)
		i = encodeVarintParams(dAtA, i, uint64(len(m.PayFreq)))
		i--
		dAtA[i] = 0x42
	}
	{
		size := m.BaseApy.Size()
		i -= size
		if _, err := m.BaseApy.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.SeparatePool {
		i--
		if m.SeparatePool {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.ProjectLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ProjectLength))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ProjectOwner) > 0 {
		i -= len(m.ProjectOwner)
		copy(dAtA[i:], m.ProjectOwner)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ProjectOwner)))
		i--
		dAtA[i] = 0x22
	}
	if m.BasicInfo != nil {
		{
			size, err := m.BasicInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SPVName) > 0 {
		i -= len(m.SPVName)
		copy(dAtA[i:], m.SPVName)
		i = encodeVarintParams(dAtA, i, uint64(len(m.SPVName)))
		i--
		dAtA[i] = 0x12
	}
	if m.Index != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Projects) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Projects) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Projects) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Submitter) > 0 {
		for iNdEx := len(m.Submitter) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Submitter[iNdEx])
			copy(dAtA[i:], m.Submitter[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.Submitter[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ProjectInfo) > 0 {
		i -= len(m.ProjectInfo)
		copy(dAtA[i:], m.ProjectInfo)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ProjectInfo)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BasicInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ProjectsUrl)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ProjectCountry)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.BusinessNumber)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.Reserved)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ProjectName)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ProjectLogo)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ProjectBrief)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ExecutiveSummary)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func (m *ProjectInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovParams(uint64(m.Index))
	}
	l = len(m.SPVName)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.BasicInfo != nil {
		l = m.BasicInfo.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ProjectOwner)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.ProjectLength != 0 {
		n += 1 + sovParams(uint64(m.ProjectLength))
	}
	if m.SeparatePool {
		n += 2
	}
	l = m.BaseApy.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.PayFreq)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.WithdrawRequestWindowSeconds != 0 {
		n += 1 + sovParams(uint64(m.WithdrawRequestWindowSeconds))
	}
	if m.PoolLockedSeconds != 0 {
		n += 1 + sovParams(uint64(m.PoolLockedSeconds))
	}
	if m.PoolTotalBorrowLimit != 0 {
		n += 1 + sovParams(uint64(m.PoolTotalBorrowLimit))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.GraceTime)
	n += 1 + l + sovParams(uint64(l))
	l = len(m.MarketId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.JuniorMinRatio.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinBorrowAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinDepositAmount.Size()
	n += 2 + l + sovParams(uint64(l))
	return n
}

func (m *Projects) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProjectInfo)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if len(m.Submitter) > 0 {
		for _, b := range m.Submitter {
			l = len(b)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BasicInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BasicInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BasicInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectsUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectsUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectCountry", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectCountry = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessNumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessNumber = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserved", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reserved = append(m.Reserved[:0], dAtA[iNdEx:postIndex]...)
			if m.Reserved == nil {
				m.Reserved = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectLogo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectLogo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectBrief", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectBrief = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutiveSummary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExecutiveSummary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProjectInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProjectInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProjectInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SPVName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SPVName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BasicInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BasicInfo == nil {
				m.BasicInfo = &BasicInfo{}
			}
			if err := m.BasicInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectOwner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectOwner = append(m.ProjectOwner[:0], dAtA[iNdEx:postIndex]...)
			if m.ProjectOwner == nil {
				m.ProjectOwner = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectLength", wireType)
			}
			m.ProjectLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectLength |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeparatePool", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SeparatePool = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseApy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseApy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayFreq", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PayFreq = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawRequestWindowSeconds", wireType)
			}
			m.WithdrawRequestWindowSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawRequestWindowSeconds |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolLockedSeconds", wireType)
			}
			m.PoolLockedSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolLockedSeconds |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolTotalBorrowLimit", wireType)
			}
			m.PoolTotalBorrowLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolTotalBorrowLimit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GraceTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.GraceTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarketId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JuniorMinRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.JuniorMinRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinBorrowAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinBorrowAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDepositAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinDepositAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Projects) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Projects: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Projects: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, &ProjectInfo{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectInfo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectInfo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = append(m.Submitter, make([]byte, postIndex-iNdEx))
			copy(m.Submitter[len(m.Submitter)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
